SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[INVTSK_ASTOBJv]
as
select
--std
  OBJ_ROWID
, OBJ_STNID = OSA_STNID
, OBJ_STATION = STN_CODE
, OBJ_STATION_DESC = STN_DESC
, OBJ_PSPID
, OBJ_PSP = PSP_CODE
, OBJ_PSPDESC = PSP_CODE
, OBJ_ITSID = INVTSK.ITS_ROWID
, OBJ_ITS = ITS_CODE
, OBJ_ITSDESC = ITS_CODE
, OBJ_OTID
, OBJ_SIGNED
, OBJ_SIGNLOC
, OBJ_VALUE 
, OBJ_CODE
, OBJ_ORG
, OBJ_DESC
, OBJ_NOTE
, OBJ_DATE
, OBJ_TIME = (dbo.e2_im_gettimefromdatetime(isnull(OBJ_DATE,'1900-01-01')))
, OBJ_STATUS
, OBJ_STATUS_DESC = (select STA_DESC from STA (nolock) where STA_CODE = OBJ_STATUS and STA_ENTITY = 'OBJ')
, OBJ_ICONSTATUS =  dbo.[GetStatusImage] ('OBJ', OBJ_STATUS)
  
, OBJ_TYPE 
, OBJ_TYPE_DESC = (select TYP_DESC from TYP (nolock) where TYP_CODE = OBJ_TYPE and TYP_ENTITY = 'OBJ')
, OBJ_TYPE2
, OBJ_TYPE2_DESC = (select TYP2.TYP2_DESC from TYP2 (nolock) join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = OBJ_TYPE and TYP_ENTITY = 'OBJ')
, OBJ_TYPE3
, OBJ_TYPE3_DESC = (select TYP3.TYP3_DESC from TYP3 (nolock) join TYP2 (nolock) on TYP2.TYP2_ROWID = TYP3.TYP3_TYP2ID join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = OBJ_TYPE and TYP_ENTITY = 'OBJ')
, OBJ_RSTATUS
, OBJ_CREUSER
, OBJ_CREUSER_DESC = dbo.UserName(OBJ_CREUSER)
, OBJ_CREDATE
, OBJ_UPDUSER
, OBJ_UPDUSER_DESC = dbo.UserName(OBJ_UPDUSER)
, OBJ_UPDDATE
, OBJ_NOTUSED
, OBJ_ID
, OBJ_GROUPID 
, OBJ_GROUP = OBG_CODE
, OBJ_GROUP_DESC = OBG_DESC
, OBJ_MANUFACID
, OBJ_MANUFAC = (select MFC_CODE from dbo.MANUFAC (nolock) where MFC_ROWID = OBJ_MANUFACID) 
, OBJ_VENDORID 
, OBJ_ASSETID = OBA_ASTID
, OBJ_ASSET = AST_CODE 
, OBJ_ASSET_DESC = AST_DESC 
, OBJ_PERSON
, OBJ_PERSON_DESC = dbo.EmpDesc(OBJ_PERSON,OBJ_ORG)  
, OBJ_PARTSLISTID
, OBJ_PARTSLIST = (select OPL_CODE from dbo.OBJPARTSLIST (nolock) where OPL_ROWID = OBJ_PARTSLISTID)
, OBJ_LOCID
, OBJ_LOC  = (select LOC_CODE from dbo.LOCATION (nolock) where LOCATION.LOC_ROWID = OBJ_LOCID)
, OBJ_CATALOGNO
, OBJ_YEAR 
, OBJ_SERIAL

, OBJ_ACCOUNTID
, OBJ_ACCOUNT = null 
, OBJ_COSTCENTERID 
, OBJ_COSTCODEID
, OBJ_COSTCODE = (select CCD_CODE from dbo.COSTCODE (nolock) where COSTCODE.CCD_ROWID = OBJ_COSTCODEID)
, OBJ_MRCID
, OBJ_MRC = (select MRC_CODE from dbo.MRC (nolock) where MRC_ROWID = OBJ_MRCID)

--udf
, OBJ_TXT01 
, OBJ_TXT02
, OBJ_TXT03
, OBJ_TXT04
, OBJ_TXT05
, OBJ_TXT06
, OBJ_TXT07
, OBJ_TXT08
, OBJ_TXT09
, OBJ_NTX01
, OBJ_NTX02 
, OBJ_NTX03
, OBJ_NTX04
, OBJ_NTX05
, OBJ_COM01
, OBJ_COM02
, OBJ_DTX01
, OBJ_DTX02
, OBJ_DTX03
, OBJ_DTX04
, OBJ_DTX05

--POWIĄZANE DOKUMENTY Z WORKFLOW
, [OT_ID]
, [OT_CODE]
, [OT_STATUS]
, [OT_STATUS_DESC]
, [OT_TYPE]
, [OT_TYPE_DESC]

from dbo.OBJ (nolock) o 
	left join dbo.OBJASSET (nolock) on OBA_OBJID = OBJ_ROWID
	left join dbo.ASSET (nolock) on AST_ROWID = OBA_ASTID
	left join dbo.OBJSTATION (nolock) os on os.OSA_OBJID = o.OBJ_ROWID
	left join dbo.STATION s (nolock) on s.STN_ROWID = OSA_STNID
	join dbo.OBJGROUP (nolock) on OBG_ROWID = OBJ_GROUPID
	left join dbo.PSP (nolock) on PSP_ROWID = OBJ_PSPID
	left join dbo.INVTSK (nolock) on ITS_ROWID = PSP_ITSID
	left join dbo.ZWFOTv (nolock) on OT_PSPID = PSP_ROWID and OT_ITSID = ITS_ROWID
where 
	isnull(OBJ_CODE,'') <> '-' 
	and isnull(OBJ_NOTUSED,0) <> 1
	and OBJ_PARENTID = OBJ_ROWID
 

 

 











GO