SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT32COMv] as
select 
 OT32COM_ROWID = COM_ROWID
,OT32COM_OT32ID = OT32_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT
,OT32_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT32 (nolock) on OT32_ZMT_ROWID = OT_ROWID and OT32_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT32'
GO