SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[OBJTECHPROTv]              
as              
select               
 [POT_ROWID],              
 [POT_CODE],              
 [POT_ORG],              
 [POT_DESC],              
 [POT_NOTE],              
 [POT_DATE],              
 [POT_STATUS],              
 [POT_STATUS_DESC] = (select STA_DESC from STA (nolock) where STA_CODE = POT_STATUS and STA_ENTITY in ('CPO', 'POT')),              
 [POT_TYPE],               
 [POT_TYPE_DESC] = (select TYP_DESC from TYP (nolock) where TYP_CODE = POT_TYPE and TYP_ENTITY IN ('CPO', 'POT')),              
 [POT_TYPE2],              
 [POT_TYPE2_DESC] = (select TYP2.TYP2_DESC from TYP2 (nolock) join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = POT_TYPE2 and TYP_ENTITY = 'POT'),              
 [POT_TYPE3],              
 [POT_TYPE3_DESC] = (select TYP3.TYP3_DESC from TYP3 (nolock) join TYP2 (nolock) on TYP2.TYP2_ROWID = TYP3.TYP3_TYP2ID join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP3.TYP3_CODE = POT_TYPE3 and TYP_ENTITY = 'POT'),              
 [POT_RSTATUS],              
 [POT_CREUSER],              
 [POT_CREUSER_DESC] = dbo.UserName(POT_CREUSER),              
 [POT_CREDATE],              
 [POT_UPDUSER],              
 [POT_UPDUSER_DESC] = dbo.UserName(POT_UPDUSER),              
 [POT_UPDDATE],              
 [POT_NOTUSED],              
 [POT_ID],              
 [POT_STNID],              
 [POT_STN] = [STN_CODE],              
 [POT_STN_DESC] = [STN_DESC],               
 [POT_TXT01],              
 [POT_TXT02],              
 [POT_TXT03],              
 [POT_TXT04],              
 [POT_TXT05],              
 [POT_TXT06],              
 [POT_TXT07],              
 [POT_TXT08],              
 [POT_TXT09],              
 [POT_NTX01],              
 [POT_NTX02],              
 [POT_NTX03],              
 [POT_NTX04],              
 [POT_NTX05],              
 [POT_COM01],              
 [POT_COM02],              
 [POT_DTX01],              
 [POT_DTX02],              
 [POT_DTX03],              
 [POT_DTX04],              
 [POT_DTX05],              
 [CHK_GU_DZR],              
 [CHK_GU_DZR_USER],              
 [CHK_GU_IT],              
 [CHK_GU_IT_USER],              
 [CHK_GU_RKB],              
 [CHK_GU_RKB_USER],              
 [CHK_GU_UR],              
 [CHK_GU_UR_USER],              
 [POT_UZASADNIENIE],              
 [POT_UCHWALA_OPIS],              
 isnull([POT_CZY_UCHWALA], 'N') POT_CZY_UCHWALA,              
 isnull([POT_CZY_DECYZJA], 'N') POT_CZY_DECYZJA,              
 [POT_DECYZJA_OPIS],              
 isnull([POT_CZY_ZAKRES], 'N') POT_CZY_ZAKRES,              
 [POT_ZAKRES_OPIS],              
 [POT_OCENA_OPIS],              
 isnull([POT_CZY_OCENA], 'N') POT_CZY_OCENA,              
 isnull([POT_CZY_EKSPERTYZY], 'N') POT_CZY_EKSPERTYZY,              
 [POT_EKSPERTYZY_OPIS],              
 [POT_SPOSOBLIKW],              
 [POT_PSP_POSKI],              
 [POT_MIESIAC],             
 [POT_ROK],             
 [STN_FILTER_ID] as [POT_STNID_VIEW],              
 [POT_ACCEPTLIST] = dbo.GetOBJTECHPROTCheck(POT_ROWID) ,             
 [POT_ATTACH_ICO]   = case when exists (select 1  from dbo.SYFiles (nolock)              
inner join dbo.DOCENTITIES (nolock) on [FileID2] = DAE_DOCUMENT              
where dae_entity = 'POT' and POT_CODE+'#'+POT_ORG = DAE_CODE) then 1 else 0 end ,          
 --[POT_CHECK_OBGID] = NULL --zmienna do procedury akceptacji na formatce       
[POT_MODERN_PROFILE], 
[POT_POTCLOSE_DATE],         
[CHK_GU_DZR_REJ],         
[CHK_GU_IT_REJ],        
[CHK_GU_RBK_REJ],        
[CHK_GU_UR_REJ]        
from [dbo].[OBJTECHPROT] (nolock)              
left join dbo.STATIONv (nolock) on STN_ROWID = [POT_STNID] 
GO