SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[OBJGROUPv]
as
select 
  OBG_ROWID
, OBG_CODE
, OBG_ORG
, OBG_DESC
, OBG_NOTE
, OBG_DATE
, OBG_TIME = (dbo.e2_im_gettimefromdatetime(isnull(OBG_DATE,'1990-01-01')))
, OBG_STATUS
, OBG_STATUS_DESC = (select STA_DESC from STA (nolock) where STA_CODE = OBG_STATUS and STA_ENTITY = 'OBG')
, OBG_TYPE
, OBG_TYPE_DESC =  (select TYP_DESC from TYP (nolock) where TYP_CODE = OBG_TYPE and TYP_ENTITY = 'OBG')
, OBG_TYPE2
, OBG_TYPE2_DESC = (select TYP2.TYP2_DESC from TYP2 (nolock) join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = OBG_TYPE and TYP_ENTITY = 'OBG')
, OBG_TYPE3
, OBG_TYPE3_DESC = (select TYP3.TYP3_DESC from TYP3 (nolock) join TYP2 (nolock) on TYP2.TYP2_ROWID = TYP3.TYP3_TYP2ID join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = OBG_TYPE and TYP_ENTITY = 'OBG')
, OBG_RSTATUS
, OBG_CREUSER
, OBG_CREUSER_DESC = dbo.UserName(OBG_CREUSER)
, OBG_CREDATE
, OBG_UPDUSER
, OBG_UPDUSER_DESC = dbo.UserName(OBG_UPDUSER)
, OBG_UPDDATE
, OBG_NOTUSED
, OBG_ID
, OBG_AUTHGROUP
, OBG_TXT01
, OBG_TXT02
, OBG_TXT03
, OBG_TXT04
, OBG_TXT05
, OBG_TXT06
, OBG_TXT07
, OBG_TXT08
, OBG_TXT09
, OBG_NTX01
, OBG_NTX02
, OBG_NTX03
, OBG_NTX04
, OBG_NTX05
, OBG_COM01
, OBG_COM02
, OBG_DTX01
, OBG_DTX02
, OBG_DTX03
, OBG_DTX04
, OBG_DTX05 
FROM dbo.OBJGROUP (nolock)
GO