SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[MOVEMENTCHECKv]
as
select
	MOC_ROWID,
	MOC_MOVID,
	MOC_OBGID,
	MOC_OBG = OBG_CODE,
	MOC_OBG_DESC = OBG_DESC,
	MOC_CHECKUSER,
	MOC_CHECKUSER_DESC = dbo.UserName(MOC_CHECKUSER),
	MOC_CHECKDATE,
	MOC_CREUSER,
	MOC_CREUSER_DESC = dbo.UserName(MOC_CREUSER),
	MOC_CREDATE,
	MOC_UPDUSER,
	MOC_UPDUSER_DESC = dbo.UserName(MOC_UPDUSER),
	MOC_UPDDATE
	
from dbo.MOVEMENTCHECK (nolock) 
	join dbo.OBJGROUP (nolock) on OBG_ROWID = MOC_OBGID
GO