SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[STENCIL_KOMv]
as
SELECT 
	KOMPLET.STS_CODE as KOM_CODE,
	KOMPLET.STS_DESC as KOM_DESC,
	ELEMENT_KOMPLETU.STS_CODE as EKOM_CODE,
	ELEMENT_KOMPLETU.STS_DESC as EKOM_DESC,
	ELEMENT_KOMPLETU.STS_NOTE as EKOM_NOTE,
	ELEMENT_KOMPLETU.STS_SIGNLOC as EKOM_SIGNLOC,
	NULL as EKOM_VALUE,
	NULL as EKOM_QTY
FROM dbo.STENCILLN (nolock)
	join dbo.STENCIL (nolock) KOMPLET on KOMPLET.STS_ROWID = STL_PARENTID and KOMPLET.STS_SETTYPE = 'KOM'
	join dbo.STENCIL (nolock) ELEMENT_KOMPLETU on ELEMENT_KOMPLETU.STS_ROWID = STL_CHILDID and ELEMENT_KOMPLETU.STS_SETTYPE = 'EKOM'
GO