SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT33v] as
 
	select  
		KROK = OT33_KROK,
		BUKRS = OT33_BUKRS,
		--WYST_SAPUSER = 'SAP',
		[WYST_SAPUSER] = (select v.OT_CODE from ZWFOT33v v WHERE v.OT33_ROWID = s.OT33_ROWID),
		WYST_NAME = OT33_IMIE_NAZWISKO,
		MTOPER = OT33_MTOPER,
		CZY_BEZ_ZM = OT33_CZY_BEZ_ZM,
		CZY_ROZ_OKR = OT33_CZY_ROZ_OKR,
		s.OT33_ROWID,
		OT33_IF_STATUS,
		OT33_IF_SENTDATE, 
		OT33_IF_EQUNR,
		OT33_ZMT_ROWID
		 
	from dbo.SAPO_ZWFOT33 s (nolock)
    

GO