SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT42v]
as
select 
		[KROK] = OT42_KROK,
		[BUKRS] = OT42_BUKRS,
		--[WYST_SAPUSER] = 'SAP',
		[WYST_SAPUSER] = right (OT_CODE,12),
		[WYST_NAME] = OT42_IMIE_NAZWISKO,
		[UZASADNIENIE] = OT42_UZASADNIENIE,
		[KOSZT] = OT42_KOSZT,
		[SZAC_WART_ODZYSKU] = OT42_SZAC_WART_ODZYSKU,
		[SPOSOBLIKW] = OT42_SPOSOBLIKW,
		[MIESIAC]=OT42_MIESIAC,
		[ROK]=OT42_ROK,
--1             We własnym zakresie
--2             Firma zewnętrzna
--3             Brak demontażu
--4             W ramach zadania inwestycyjnego
--5             Sprzedaż
		[PSP] = OT42_PSP,
		[CZY_UCHWALA] = OT42_CZY_UCHWALA,
		[CZY_DECYZJA] = OT42_CZY_DECYZJA,
		[CZY_ZAKRES] = OT42_CZY_ZAKRES,
		[CZY_OCENA] = OT42_CZY_OCENA,
		[CZY_EKSPERTYZY] = OT42_CZY_EKSPERTYZY,
		[UCHWALA_OPIS] = OT42_UCHWALA_OPIS,
		[DECYZJA_OPIS] = OT42_DECYZJA_OPIS,
		[ZAKRES_OPIS] = OT42_ZAKRES_OPIS,
		[OCENA_OPIS] = OT42_OCENA_OPIS,
		[EKSPERTYZY_OPIS] = OT42_EKSPERTYZY_OPIS,	
		s.[OT42_ROWID],
		[OT42_IF_STATUS],
		[DOC_NUM] = OT42_IF_EQUNR,
		[DOC_YEAR] = OT42_IF_YEAR,
		[AKCJA] = OT42_IF_AKCJA,
		[GUID] = OT_ID
	from dbo.SAPO_ZWFOT42 s (nolock)
	inner join dbo.ZWFOT on OT_ROWID = OT42_ZMT_ROWID
GO