SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[ZWFOT40LNv]
as
select
 OT40LN_LP = ROW_NUMBER() OVER(PARTITION BY OT40LN_OT40ID ORDER BY OT40LN_ANLN1, OT40LN_ANLN2 ASC)
,OT40LN_ROWID
,OT40LN_BUKRS
,OT40LN_ANLN1
,OT40LN_ANLN1_POSKI
,OT40LN_ANLN1_POSKI_DESC = (select AST_DESC from dbo.ASSET (nolock) where AST_CODE = OT40LN_ANLN1_POSKI and AST_SUBCODE = OT40LN_ANLN2)
,OT40LN_ANLN2
,OT40LN_PROC
,OT40LN_OPIS
,OT40LN_ZMT_ROWID
,OT40LN_OT40ID 
	
--dane pozycji ZMT
,OTL_ROWID
,OTL_OTID
,OTL_OBJID
,OTL_OBJ = OBJ_CODE
,OTL_OBJ_DESC = OBJ_DESC
,OTL_CODE
,OTL_ORG
,OTL_STATUS
,OTL_STATUS_DESC = (select STA_DESC from STA (nolock) where STA_CODE = OT_STATUS and STA_ENTITY = 'OT40')
,OTL_TYPE
,OTL_RSTATUS = OT_RSTATUS
,OTL40_RSTATUS = OT_RSTATUS
,OTL_ID
,OTL_CREUSER
,OTL_CREUSER_DESC = dbo.UserName(OTL_CREUSER)
,OTL_CREDATE
,OTL_UPDUSER
,OTL_UPDUSER_DESC = dbo.UserName(OTL_UPDUSER)
,OTL_UPDDATE 

--dane nagłówka
,OT_ID
,OT_CODE
,OT_STATUS_DESC = (select STA_DESC from STA (nolock) where STA_CODE = OT_STATUS and STA_ENTITY = 'OT40')
,OT40_IF_EQUNR 
	
--dane pozycji PL
,OTL_OTLID
from dbo.SAPO_ZWFOT40LN (nolock)
join dbo.SAPO_ZWFOT40 (nolock) on OT40_ROWID = OT40LN_OT40ID
join dbo.ZWFOTLN (nolock) on OTL_ROWID = OT40LN_ZMT_ROWID
join dbo.ZWFOT (nolock) on OT_ROWID = OTL_OTID --takie połączenie również prawidłowe: ZWFOT.OT_ROWID = OT40_ZMT_ROWID
left join dbo.PSP (nolock) on PSP.PSP_ROWID = OT_PSPID
left join dbo.INVTSK (nolock) on INVTSK.ITS_ROWID = OT_ITSID
left join dbo.OBJ (nolock) on OBJ.OBJ_ROWID = OTL_OBJID
	 
where 
OT40_IF_STATUS <> 4
and OT_TYPE = 'SAPO_ZWFOT40'
and isnull(OTL_NOTUSED,0) = 0
GO