SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[MODERN_PROFILE_LNv]  
AS   
SELECT  
 MDL_ROWID   
,MDL_MDPID   
,MDL_CODE = (select MDP_CODE from MODERN_PROFILE where MDP_ROWID = MDL_MDPID)  
,MDL_KSTCODE 
, MDL_KSTDESC = (select CCF_DESC from [dbo].[COSTCLASSIFICATION] where CCF_CODE = MDL_KSTCODE)   
,MDL_CREDATE   
,MDL_CREUSER   
,MDL_UPDDATE   
,MDL_UPDUSER   
FROM MODERN_PROFILE_LN
GO