SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT32DONv]
as
select 
LP = OT32DON_LP,
BUKRS = OT32DON_BUKRS,    
ANLN1 = isnull(OT32DON_ANLN1,''), 
ANLN2 = isnull(OT32DON_ANLN2,''),   	 
ANLN1_DO = isnull(OT32DON_ANLN1_DO,''),
ANLN2_DO = isnull(OT32DON_ANLN2_DO,''),
OT32DON_ROWID,
OT32DON_ZMT_ROWID,
OT32DON_OT32ID
from dbo.SAPO_ZWFOT32DON (nolock)
inner join dbo.ZWFOTDON(nolock) on OTD_ROWID = OT32DON_ZMT_ROWID and OTD_NOTUSED = 0
GO