SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[STENCILv]
as
select
--std
  STS_ROWID  
, STS_PSEID
, STS_PSE = PSE_CODE
, STS_PSEDESC = PSE_CODE
, STS_SETTYPE 
, STS_SETTYPEDESC = STT_DESC 
, STS_SIGNED
, STS_SIGNLOC
, STS_VALUE 
, STS_CODE
, STS_ORG
, STS_DESC
, STS_NOTE
, STS_DATE
, STS_TIME = (dbo.e2_im_gettimefromdatetime(isnull(STS_DATE,'1900-01-01')))
, STS_STATUS
, STS_STATUS_DESC = (select STA_DESC from STA (nolock) where STA_CODE = STS_STATUS and STA_ENTITY = 'STS')
, STS_ICONSTATUS =  dbo.[GetStatusImage] ('STS', STS_STATUS)
  
, STS_TYPE 
, STS_TYPE_DESC = (select TYP_DESC from TYP (nolock) where TYP_CODE = STS_TYPE and TYP_ENTITY = 'OBJ')
, STS_TYPE2
, STS_TYPE2_DESC = (select TYP2.TYP2_DESC from TYP2 (nolock) join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP2.TYP2_CODE = STS_TYPE2 and TYP_ENTITY = 'OBJ')
, STS_TYPE3
, STS_TYPE3_DESC = (select TYP3.TYP3_DESC from TYP3 (nolock) join TYP2 (nolock) on TYP2.TYP2_ROWID = TYP3.TYP3_TYP2ID join TYP (nolock) on TYP.TYP_ROWID = TYP2.TYP2_TYP1ID where TYP3.TYP3_CODE = STS_TYPE3 and TYP_ENTITY = 'OBJ')
, STS_RSTATUS
, STS_CREUSER
, STS_CREUSER_DESC = dbo.UserName(STS_CREUSER)
, STS_CREDATE
, STS_UPDUSER
, STS_UPDUSER_DESC = dbo.UserName(STS_UPDUSER)
, STS_UPDDATE
, STS_NOTUSED
, STS_ID
, STS_GROUPID 
, STS_GROUP = OBG_CODE
, STS_GROUP_DESC = OBG_DESC
, STS_MANUFACID
, STS_MANUFAC = (select MFC_CODE from dbo.MANUFAC (nolock) where MFC_ROWID = STS_MANUFACID) 
, STS_VENDORID  
, STS_PERSON
, STS_PERSON_DESC = dbo.EmpDesc(STS_PERSON,STS_ORG)  
, STS_PARTSLISTID
, STS_PARTSLIST = (select OPL_CODE from dbo.OBJPARTSLIST (nolock) where OPL_ROWID = STS_PARTSLISTID)
, STS_LOCID
, STS_LOC  = (select LOC_CODE from dbo.LOCATION (nolock) where LOCATION.LOC_ROWID = STS_LOCID)
, STS_CATALOGNO
, STS_YEAR 
, STS_SERIAL
, STS_DEFAULT_KST
, STS_DEFAULT_KST_DESC = (select CCF_DESC from COSTCLASSIFICATIONv where CCF_CODE = STS_DEFAULT_KST)

, STS_ACCOUNTID
, STS_ACCOUNT = null
, STS_COSTCODEID
, STS_COSTCODE = (select CCD_CODE from dbo.COSTCODE (nolock) where COSTCODE.CCD_ROWID = STS_COSTCODEID)
, STS_MRCID
, STS_MRC = (select MRC_CODE from dbo.MRC (nolock) where MRC_ROWID = STS_MRCID)
, STS_SAP_CHK

--udf
, STS_TXT01 
, STS_TXT02
, STS_TXT03
, STS_TXT04
, STS_TXT05
, STS_TXT06
, STS_TXT07
, STS_TXT08
, STS_TXT09
, STS_NTX01
, STS_NTX02 
, STS_NTX03
, STS_NTX04
, STS_NTX05
, STS_COM01
, STS_COM02
, STS_DTX01
, STS_DTX02
, STS_DTX03
, STS_DTX04
, STS_DTX05

--automatycznie wystawia dany szablon gdy wystawione zamówienie na ten PSP
, STS_AUTO_PSP
, STS_ROTARY
, STS_PM_TOSEND

from dbo.[STENCIL] (nolock) o  
	join SETTYPE (nolock) on STT_CODE = STS_SETTYPE
	left join OBJGROUP (nolock) on OBG_ROWID = STS_GROUPID
	left join PSPEDIT (nolock) on PSE_ROWID = STS_PSEID
where isnull(STS_CODE,'') <> '-' and isnull(STS_NOTUSED,0) <> 1
GO