SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[Password_Parameters_VV]
AS
	 SELECT [KeyCode], [ModuleCode], [SettingValue], [Description]  
	 FROM dbo.SYSettings  
	 WHERE ModuleCode = 'Vision' AND KeyCode IN ('SEC_PASS_EXPIRATION_DAYS', 'SEC_PASS_EXPIRATION_DAYS_INFO', 'SEC_PASS_HIST_LENGTH',  
	 'SEC_PASS_HIST_DAYS','PASS_LENGTH', 'PASS_NONALPHANUMERIC_CHARACTERS_COUNT', 'PASS_UPPER_CHARACTERS_COUNT',   
	 'PASS_LOWER_CHARACTERS_COUNT','PASS_NUMERICAL_CHARACTERS_COUNT', 'PASS_EQUAL_USERID')
GO