SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[ZWFOT32_HISTv]
as
SELECT 

	[OT32_ROWID]
	,[OT32_KROK]
	,[OT32_BUKRS]
	,[OT32_SAPUSER]
	,[OT32_IMIE_NAZWISKO]
	,[OT32_IF_STATUS]
	,[OT32_IF_SENTDATE] 
	,[OT32_IF_EQUNR] 
	,[OT32_ZMT_ROWID]    

	--dane nagłówka
	,[OT_ROWID]
	,[OT_PSPID]
	--,[OT_PSP] = [PSP_CODE]
	--,[OT_PSP_DESC] = [PSP_DESC]
	,[OT_ITSID]
	--,[OT_ITS] = [ITS_CODE]
	--,[OT_ITS_DESC] = [ITS_DESC]
	--,[OT_OBJID]
	--,[OT_OBJ] = [OBJ_CODE]
	--,[OT_OBJ_DESC] = [OBJ_DESC]
	,[OT_CODE]
	,[OT_ORG]
	,[OT_STATUS]
	,[OT_STATUS_DESC] = (select STA_DESC from STA (nolock) where STA_CODE = [OT_STATUS] and STA_ENTITY = 'OT32')
	,[OT_TYPE]
	,[OT_RSTATUS]
	,[OT32_RSTATUS] = [OT_RSTATUS]
	,[OT_ID]
	,[OT_CREUSER]
	,[OT_CREUSER_DESC] = dbo.UserName(OT_CREUSER)
	,[OT_CREDATE]
	,[OT_UPDUSER]
	,[OT_UPDUSER_DESC] = dbo.UserName(OT_UPDUSER)
	,[OT_UPDDATE] 
FROM [dbo].[SAPO_ZWFOT32] (nolock)
	join [dbo].[ZWFOT] (nolock) on [ZWFOT].OT_ROWID = [OT32_ZMT_ROWID]
where 
	[OT_TYPE] = 'SAPO_ZWFOT32'
   


GO