SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE  view [dbo].[VENDORv]
as
select 
	  VEN_ROWID
	, VEN_CODE
	, VEN_ORG
	, VEN_DESC
	, VEN_NOTE
	, VEN_DATE
	, VEN_TIME = (dbo.e2_im_gettimefromdatetime(isnull(VEN_DATE,'1990-01-01')))
	, VEN_STATUS
	, VEN_STATUS_DESC = sta.DES_TEXT
	, VEN_TYPE
	, VEN_TYPE_DESC = typ1.DES_TEXT
	, VEN_TYPE2
	, VEN_TYPE2_DESC = typ2.DES_TEXT
	, VEN_TYPE3
	, VEN_TYPE3_DESC = typ3.DES_TEXT
	, VEN_RSTATUS
	, VEN_CREUSER
	, VEN_CREUSER_DESC = dbo.UserName(VEN_CREUSER)
	, VEN_CREDATE
	, VEN_UPDUSER
	, VEN_UPDUSER_DESC = dbo.UserName(VEN_UPDUSER)
	, VEN_UPDDATE
	, VEN_NOTUSED
	, VEN_ID
	, VEN_TXT01, VEN_TXT02, VEN_TXT03, VEN_TXT04, VEN_TXT05, VEN_TXT06, VEN_TXT07, VEN_TXT08, VEN_TXT09
	, VEN_NTX01, VEN_NTX02, VEN_NTX03, VEN_NTX04, VEN_NTX05
	, VEN_COM01, VEN_COM02
	, VEN_DTX01, VEN_DTX02, VEN_DTX03, VEN_DTX04, VEN_DTX05
	, VEN_CITY = isnull(VEN_CITY, VEN_SAP_MCOD3)
	, VEN_STREET = isnull(VEN_STREET, VEN_SAP_STRAS)
	, VEN_STATE
	, VEN_ZIPCODE = isnull(VEN_ZIPCODE, VEN_SAP_PSTLZ)
	, VEN_COUNTY
	, VEN_COUNTRY
	, VEN_PHONE1
	, VEN_PHONE2
	, VEN_PHONE3
	, VEN_FAX
	, VEN_EMAIL
	, VEN_WWW
	, VEN_LINEOFBUSINESSID
	, VEN_REGON
	, VEN_NIP = isnull(VEN_NIP, VEN_SAP_STCD1)
	, VEN_CURR
	, VEN_PAYTYPEID
	, VEN_PAYTYPECODE = (select PAY_code from paytype (nolock) where PAY_ROWID = VEN_PAYTYPEID)
	, VEN_EMPCODE
	, VEN_LEGALFORM
	, VEN_PURCHPOOL
	, VEN_DESTINATIONCODE
	, VEN_DELIVERYTERM
	, VEN_AXAID
	, VEN_ISSERVICE
	, VEN_CONTACTPERSON
	, VEN_LANGID = LangID
	, VEN_SAP_Active
	, VEN_SAP_LIFNR
	, VEN_SAP_LAND1
	, VEN_SAP_NAME1
	, VEN_SAP_MCOD1
	, VEN_SAP_NAME2
	, VEN_SAP_NAME3
	, VEN_SAP_NAME4
	, VEN_SAP_ORT01
	, VEN_SAP_ORT02
	, VEN_SAP_PFACH
	, VEN_SAP_PSTL2
	, VEN_SAP_PSTLZ
	, VEN_SAP_MCOD2
	, VEN_SAP_STRAS
	, VEN_SAP_ADRNR
	, VEN_SAP_MCOD3
	, VEN_SAP_ANRED
	, VEN_SAP_BEGRU
	, VEN_SAP_ERDAT
	, VEN_SAP_ERNAM
	, VEN_SAP_KTOKK
	, VEN_SAP_KUNNR
	, VEN_SAP_SPRAS
	, VEN_SAP_STCD1
	, VEN_SAP_STCD2
from dbo.VENDOR (nolock)
cross join VS_Langs
left join dbo.DESCRIPTIONS_VENv sta(nolock) on sta.DES_TYPE = 'STAT' and sta.DES_CODE = VEN_STATUS and sta.DES_LANGID = LangID
left join dbo.DESCRIPTIONS_VENv typ1(nolock) on typ1.DES_TYPE = 'TYP1' and typ1.DES_CODE = VEN_TYPE and typ1.DES_LANGID = LangID
left join dbo.DESCRIPTIONS_VENv typ2(nolock) on typ2.DES_TYPE = 'TYP2' and typ2.DES_CODE = VEN_TYPE+'#'+VEN_TYPE2 and typ2.DES_LANGID = LangID
left join dbo.DESCRIPTIONS_VENv typ3(nolock) on typ3.DES_TYPE = 'TYP3' and typ3.DES_CODE = VEN_TYPE+'#'+VEN_TYPE2+'#'+VEN_TYPE3 and typ3.DES_LANGID = LangID
where VEN_SAP_KTOKK not in ('PRAC', 'CPN', 'FLOT', 'NAFT')
and VEN_NOTUSED = 0
GO