SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT40COMv] as
select 
	 OT40_ZMT_ROWID 
	,OT_ROWID
	,OT40COM_ROWID = COM_ROWID
	,OT40COM_OT40ID = OT40_ROWID
	,TDFORMAT = 'T'
	,TDLINE = TXT
	,OT40_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT40 (nolock) on OT40_ZMT_ROWID = OT_ROWID and OT40_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)  
where OT_TYPE = 'SAPO_ZWFOT40'
GO