SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT42COMv] as  
select   
 OT42_ZMT_ROWID
,OT_ROWID
,OT42COM_ROWID = COM_ROWID
,OT42COM_OT42ID = OT42_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT,
OT42_IF_STATUS
from dbo.COMMENTS (nolock)   
join ZWFOT (nolock) on OT_ID = COM_ID  
join SAPO_ZWFOT42 (nolock) on OT42_ZMT_ROWID = OT_ROWID --and OT42_IF_STATUS = 1  
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT42'  
GO