SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[CPO_REPORT_GROUPv]
as
select POL_POTID,POL_GROUP,STN_CODE,STN_SUM=sum(POL_PARTIAL_NETTO) 
from  [dbo].[CPO_REPORT_LINESv] 
group by POL_POTID,POL_GROUP,STN_CODE
GO