SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT41COMv] as
select 
 OT41_ZMT_ROWID 
,OT_ROWID
,OT41COM_ROWID = COM_ROWID
,OT41COM_OT41ID = OT41_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT
,OT41_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT41 (nolock) on OT41_ZMT_ROWID = OT_ROWID and OT41_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT41'
GO