SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT11CHARv] as
 	select 
		TDFORMAT = OT11CHAR_TDFORMAT, 
		TDLINE = OT11CHAR_TDLINE,
		OT11CHAR_ROWID,
		OT11CHAR_OT11ID
	from dbo.SAPO_ZWFOT11CHAR (nolock)
	where OT11CHAR_ROWID in 
		(select   
			max(X1.OT11CHAR_ROWID)
		from dbo.SAPO_ZWFOT11CHAR (nolock) X1
		group by X1.OT11CHAR_OT11ID)
	 
GO