SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT21COMv] as
select 
 OT21COM_ROWID = COM_ROWID
,OT21COM_OT21ID = OT21_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT
,OT21_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT21 (nolock) on OT21_ZMT_ROWID = OT_ROWID and OT21_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT21'
GO