SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO




CREATE view [dbo].[STSPSPOBJ_COUNTv]
as
select 
	PARENT.STS_ROWID  as STS_PARENTID,
	PARENT.STS_CODE as STS_PARENT,
	PARENT.STS_DESC as STS_PARENTDESC,
	CHILD.STS_ROWID as STS_CHILDID,
	CHILD.STS_CODE as STS_CHILD,
	CHILD.STS_DESC as STS_CHILDDESC,
	OBJ.OBJ_PSPID as OBJ_PSPID,
	PSP.PSP_CODE as OBJ_PSP,
	PSP.PSP_DESC as OBJ_PSPDESC,
	INO.INO_ROWID as INO_ROWID,
	 count(OBJ_ROWID)  as OBJ_COUNT,
	OBJ_VALUE,
	STL_DEFAULT_NUMBER
from STENCIL (nolock) PARENT
	join STENCILLN (nolock) on STL_PARENTID = PARENT.STS_ROWID 
	join STENCIL (nolock) CHILD on STL_CHILDID = CHILD.STS_ROWID 
	join OBJ (nolock) on CHILD.STS_ROWID = OBJ_STSID
	join INVTSK_NEW_OBJ (nolock) INO on INO_ROWID = OBJ_INOID
	join PSP (nolock) on PSP.PSP_ROWID = INO_PSPID
group by   
	PARENT.STS_ROWID,
	PARENT.STS_CODE,
	PARENT.STS_DESC,
	CHILD.STS_ROWID,
	CHILD.STS_CODE,
	CHILD.STS_DESC,
	OBJ.OBJ_PSPID,
	PSP.PSP_CODE,
	PSP.PSP_DESC,
	INO.INO_ROWID,
	OBJ_VALUE,
	STL_DEFAULT_NUMBER
	 





GO