SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[CPO_OBJECT_STENCILv]    
as     
select    
CPT_ROWID     
,CPT_CPOID    
,CPT_STSID
,CPT_STS = STS_CODE
,CPT_STSDESC = STS_DESC
,CPT_TYPEID     
,CPT_TYPE = TYP_CODE  
,CPT_TYPE_DESC = TYP_DESC  
,CPT_TYPE2ID    
, CPT_TYPE2 = TYP2_CODE  
,CPT_TYPE2_DESC = TYP2_DESC  
from CPO_OBJECT_STENCIL
join STENCIL on CPT_STSID = STS_ROWID
LEFT JOIN TYP on CPT_TYPEID = TYP_ROWID  
LEFT JOIN TYP2 on CPT_TYPE2ID = TYP2_ROWID
GO