SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT33COMv] as
select 
 OT33COM_ROWID = COM_ROWID
,OT33COM_OT33ID = OT33_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT
,OT33_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT33 (nolock) on OT33_ZMT_ROWID = OT_ROWID and OT33_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT33'
GO