SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view  [dbo].[SAPO_ZWFOT12COMv] as
select 
 OT12COM_ROWID = COM_ROWID
,OT12COM_OT12ID = OT12_ROWID
,TDFORMAT = 'T'
,TDLINE = TXT
,OT12_IF_STATUS
from dbo.COMMENTS (nolock) 
join ZWFOT (nolock) on OT_ID = COM_ID
join SAPO_ZWFOT12 (nolock) on OT12_ZMT_ROWID = OT_ROWID and OT12_IF_STATUS = 1
cross apply dbo.SAPO_COMMENT_Split(COM_TEXT, 132)
where OT_TYPE = 'SAPO_ZWFOT12'
GO