SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create view [dbo].[SP_REQUEST_MAIL_RECIPIENTs]
as
select OBJ_CODE, OBJ_DESC, STN_DESC,STA2.STH_DATE, STA1.STH_USER, EMAIL 
from OBJ
join SP_REQUEST on SRQ_OBJID = OBJ_ROWID
join dbo.STATION s_to (nolock) on s_to.STN_ROWID = SRQ_STNID_TO 
join STAHIST Sta1 on STA1.STH_ID = SRQ_ID AND STA1.STH_NEW = 'SRQ_001' and STA1.STH_ENTITY = 'SRQ'
join STAHIST Sta2 on STA2.STH_ID = SRQ_ID AND STA2.STH_NEW = 'SRQ_007' and STA2.STH_ENTITY = 'SRQ'
join SYUSERS on UserID = STA1.STH_USER
where SRQ_STATUS = 'SRQ_007'
and SRQ_TYPE in ('SERWIS','SERWIS_ZAST')
and datediff(day, STA2.STH_DATE, getdate()) = 7
GO