SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT21v] as
 
	select 
	 
		SERNR = isnull(OT21_SERNR,''),
		POSNR = isnull(OT21_POSNR,''),
		KOSTL = OT21_KOSTL, 
		GDLGRP = isnull(OT21_GDLGRP,''), 
		MUZYTK = left(OT21_MUZYTK,20),
		BUKRS = OT21_BUKRS,
		WYST_SAPUSER = OT21_SAPUSER,
		WYST_NAME = OT21_IMIE_NAZWISKO,
		ZZ_NR_FORM = OT21_NR_FORM,
		ZZ_TYP_DOK = OT21_TYP_DOK,
		ZZ_POZ_FORM = OT21_POZ_FORM,
		ZZ_NR_DOK = OT21_NR_DOK,
		CZY_FORM = isnull(OT21_CZY_FORM,2),	
		s.OT21_ROWID,
		OT21_IF_STATUS,
		OT21_IF_SENTDATE, 
		OT21_IF_EQUNR
 
	from dbo.SAPO_ZWFOT21 s (nolock)
   
 --exec dbo.SAPO_OT21
 








GO