SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[STSANOOBJ_COUNTv]
as
select 
	PARENT.STS_ROWID  as STS_PARENTID,
	PARENT.STS_CODE as STS_PARENT,
	PARENT.STS_DESC as STS_PARENTDESC,
	CHILD.STS_ROWID as STS_CHILDID,
	CHILD.STS_CODE as STS_CHILD,
	CHILD.STS_DESC as STS_CHILDDESC,
	OBJ.OBJ_ANOID as OBJ_ANOID,
	count(OBJ_ROWID)  as OBJ_COUNT
from STENCIL (nolock) PARENT
	join STENCILLN (nolock) on STL_PARENTID = PARENT.STS_ROWID 
	join STENCIL (nolock) CHILD on STL_CHILDID = CHILD.STS_ROWID 
	join OBJ (nolock) on CHILD.STS_ROWID = OBJ_STSID
	join ASTINW_NEW_OBJ (nolock) ANO on ANO.ANO_ROWID = OBJ_ANOID
group by   
	PARENT.STS_ROWID,
	PARENT.STS_CODE,
	PARENT.STS_DESC,
	CHILD.STS_ROWID,
	CHILD.STS_CODE,
	CHILD.STS_DESC,
	OBJ.OBJ_ANOID
GO