SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

create view [dbo].[POB_WIEKv]
as 
select PBW_ROWID
,PBW_GROUP_CODE
,PBW_GROUPDESC = (select TYP_DESC from TYP where TYP_ENTITY = 'OBJ' and TYP_CODE = PBW_GROUP_CODE)
,PBW_WIEK
from POB_WIEK
GO