SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[ZMTvsFIAA_ST]
as
select --top 100
 BURKS = AST_SAP_BUKRS
,ANLN1 = AST_SAP_ANLN1
,ANLN2 = AST_SAP_ANLN2
,KOSTL = AST_SAP_KOSTL
,ACTIVE = AST_SAP_ACTIVE
from ASSET
inner join COSTCODE on CCD_ROWID = AST_CCDID
inner join dbo._import_stacji_paczki on MPK = CCD_CODE
--order by AST_SAP_ANLN1, AST_SAP_ANLN2
GO