SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT40v]
as
select 
		[KROK] = OT40_KROK,
		[BUKRS] = OT40_BUKRS,
		--[WYST_SAPUSER] = 'SAP',
		[WYST_SAPUSER] = right(OT_CODE,12),
		[WYST_NAME] = OT40_IMIE_NAZWISKO,
		[PL_DOC_NUM] = isnull(OT40_PL_DOC_NUM,''),
		[PL_DOC_YEAR] = OT40_PL_DOC_YEAR,
		s.[OT40_ROWID],
		[OT40_IF_STATUS],
		[DOC_NUM] = OT40_IF_EQUNR,
		[DOC_YEAR] = OT40_IF_YEAR,
		[AKCJA] = OT40_IF_AKCJA,
		[GUID] = OT_ID
		
	from dbo.SAPO_ZWFOT40 s (nolock)
	inner join dbo.ZWFOT on OT_ROWID = OT40_ZMT_ROWID
GO