SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[SAPO_ZWFOT32LNv]
as

select 
	 
	LP = OT32LN_LP,
	BUKRS = left(OT32LN_BUKRS,4),
	ANLN1 = left(OT32LN_ANLN1,12),
	DT_WYDANIA = convert(nvarchar(10),OT32LN_DT_WYDANIA, 120),
	MPK_WYDANIA = left(OT32LN_MPK_WYDANIA,10),
	GDLGRP = left(OT32LN_GDLGRP,8),
	DT_PRZYJECIA = convert(nvarchar(10),OT32LN_DT_PRZYJECIA, 120),
	MPK_PRZYJECIA = left(OT32LN_MPK_PRZYJECIA,10),
	UZYTKOWNIK = left(OT32LN_UZYTKOWNIK,8),
	PRACOWNIK = OT32LN_PRACOWNIK,
	ANLN1_PRZYJECIA = OT32LN_ANLN1_PRZYJECIA,
 	OT32LN_ROWID,
	OT32LN_ZMT_ROWID,
	OT32LN_OT32ID 
	
from dbo.SAPO_ZWFOT32LN (nolock) 
	join dbo.ZWFOTLN (nolock) on OTL_ROWID = OT32LN_ZMT_ROWID
where
	OTL_NOTUSED = 0
	 
 
GO