SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE view [dbo].[SAPO_ZWFOT31LNv]
as

select 

	LP  = ROW_NUMBER() OVER(PARTITION BY [OT31LN_OT31ID] ORDER BY [OT31LN_ANLN1] ASC),
	BUKRS = isnull(OT31LN_BUKRS,''),
	ANLN1 = isnull(OT31LN_ANLN1,''), 
	UZASADNIENIE = isnull(OT31LN_UZASADNIENIE,''),
	DT_WYDANIA = isnull(convert(nvarchar(10),OT31LN_DT_WYDANIA,120),''),
	MPK_WYDANIA = isnull(OT31LN_MPK_WYDANIA,''),
	GDLGRP = isnull(OT31LN_GDLGRP,''),
	DT_PRZYJECIA = isnull(convert(nvarchar(10),OT31LN_DT_PRZYJECIA,120),''),
	MPK_PRZYJECIA = isnull(OT31LN_MPK_PRZYJECIA,''),
	UZYTKOWNIK = isnull(OT31LN_UZYTKOWNIK,''),
	PRACOWNIK = isnull(OT31LN_PRACOWNIK,''),
	OT31LN_ROWID,
	OT31LN_ZMT_ROWID,
	OT31LN_OT31ID 
from dbo.SAPO_ZWFOT31LN (nolock) 
	join dbo.ZWFOTLN (nolock) on OTL_ROWID = OT31LN_ZMT_ROWID
where
	OTL_NOTUSED = 0
	 
 
GO