SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[OBJASSETv]  
as  
select  
OBJ_ROWID  
,OBJ_CODE  
,OBJ_DESC  
,OBJ_PARENTID  
,OBJ_STATUS  
,OBJ_NOTUSED  
,AST_ROWID  
,AST_CODE  
,AST_SUBCODE  
,AST_DESC  
,AST_NOTUSED 
,AST_SAP_URWRT 
from dbo.OBJ  
inner join dbo.OBJASSET on OBA_OBJID = OBJ_ROWID  
inner join dbo.ASSET on AST_ROWID = OBA_ASTID  
GO