SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create   view [dbo].[OTPOLv]
as
select
 OT_ROWID
,OT_ID
,OTO_OBJID
,POL_TO_STNID
from dbo.ZWFOTOBJ
join dbo.ZWFOT on OT_ROWID = OTO_OTID
join dbo.OBJTECHPROTLN on coalesce(POL_OT33ID, POL_OT31ID, POL_OT42ID, POL_OT41ID, POL_OT32ID) = OT_ROWID and POL_OBJID = OTO_OBJID
union all
select
 OT_ROWID
,OT_ID
,OTO_OBJID
,SRQ_STNID_TO
from dbo.ZWFOTOBJ
join dbo.ZWFOT on OT_ROWID = OTO_OTID
join dbo.SP_REQUEST on coalesce(SRQ_OT33ID, SRQ_OT31ID, SRQ_OT42ID, SRQ_OT41ID, SRQ_OT32ID) = OT_ROWID and SRQ_OBJID = OTO_OBJID
GO