SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create view [dbo].[POB_PRZEBIEGv]
as 
select PBP_ROWID
,PBP_GROUP_CODE
,PBP_GROUPDESC = (select TYP_DESC from TYP where TYP_ENTITY = 'OBJ' and TYP_CODE = PBP_GROUP_CODE)
,PBP_PRZEBIEG
from POB_PRZEBIEG
GO