SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE view [dbo].[KLASYFIKATOR5v]
as
select     
	  KL5_ROWID
	, KL5_CODE
	, KL5_ORG
	, KL5_DESC
	, KL5_NOTUSED
	, KL5_CREUSER
	, KL5_CREDATE
	, KL5_UPDUSER
	, KL5_UPDDATE
	, KL5_SAP_GDLGRP
	, KL5_SAP_GDLGRP_TXT
	, KL5_SAP_ACTIVE

from dbo.KLASYFIKATOR5 (nolock)
	where KL5_SAP_ACTIVE = 1
	and left (KL5_CODE,1) = '7'
	
	 
GO