SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[M_OBJ_sync]
as
 BEGIN
	UPDATE OBJ
	SET OBJ_SIGNEDEXISTS = a.SIGNEDEXISTS
	FROM (SELECT TOP 1 SIGNEDEXISTS, ROWID FROM M_OBJ ORDER BY CREDATE DESC) AS a
	WHERE OBJ.OBJ_ROWID = a.ROWID;

	DELETE FROM M_OBJ
 END
GO