SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DBM_GUS_Values_UPDATE](
    @GUS_year int, 
    @GUS_percent numeric(8,3), 
    @GUS_CREUSER nvarchar(80), 
    @GUS_CREDATE datetime, 
    @GUS_UPDUSER nvarchar(80), 
    @GUS_UPDDATE datetime, 
    @GUS_TXT01 nvarchar(30), 
    @GUS_TXT02 nvarchar(30), 
    @GUS_TXT03 nvarchar(60), 
    @GUS_TXT04 nvarchar(60), 
    @GUS_TXT05 nvarchar(120), 
    @GUS_TXT06 nvarchar(120), 
    @GUS_NTX01 numeric(10,3), 
    @GUS_NTX02 numeric(10,3), 
    @GUS_NTX03 numeric(10,3), 
    @GUS_DTX01 datetime, 
    @GUS_DTX02 datetime
) AS
IF NOT EXISTS (SELECT * FROM [GUS_Values] WHERE 1=1)
    INSERT INTO [GUS_Values] ([GUS_year], [GUS_percent], [GUS_CREUSER], [GUS_CREDATE], [GUS_UPDUSER], [GUS_UPDDATE], [GUS_TXT01], [GUS_TXT02], [GUS_TXT03], [GUS_TXT04], [GUS_TXT05], [GUS_TXT06], [GUS_NTX01], [GUS_NTX02], [GUS_NTX03], [GUS_DTX01], [GUS_DTX02])
    VALUES (@GUS_year, @GUS_percent, @GUS_CREUSER, @GUS_CREDATE, @GUS_UPDUSER, @GUS_UPDDATE, @GUS_TXT01, @GUS_TXT02, @GUS_TXT03, @GUS_TXT04, @GUS_TXT05, @GUS_TXT06, @GUS_NTX01, @GUS_NTX02, @GUS_NTX03, @GUS_DTX01, @GUS_DTX02)
ELSE
    UPDATE [GUS_Values] SET [GUS_year] = @GUS_year, [GUS_percent] = @GUS_percent, [GUS_CREUSER] = @GUS_CREUSER, [GUS_CREDATE] = @GUS_CREDATE, [GUS_UPDUSER] = @GUS_UPDUSER, [GUS_UPDDATE] = @GUS_UPDDATE, [GUS_TXT01] = @GUS_TXT01, [GUS_TXT02] = @GUS_TXT02, [GUS_TXT03] = @GUS_TXT03, [GUS_TXT04] = @GUS_TXT04, [GUS_TXT05] = @GUS_TXT05, [GUS_TXT06] = @GUS_TXT06, [GUS_NTX01] = @GUS_NTX01, [GUS_NTX02] = @GUS_NTX02, [GUS_NTX03] = @GUS_NTX03, [GUS_DTX01] = @GUS_DTX01, [GUS_DTX02] = @GUS_DTX02 WHERE 1=1
GO