SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROC [dbo].[CPO_TYPE_InsUpd]
(
 @TYP_ROWID	int
,@TYP2_ROWID int
,@TYP2_CODE	nvarchar(30)
,@TYP2_DESC	nvarchar(80)

)AS
	BEGIN
		IF NOT EXISTS (SELECT 1 FROM TYP2 WHERE TYP2_ROWID = @TYP2_ROWID AND TYP2_TYP1ID = @TYP_ROWID)				
			BEGIN
				INSERT INTO TYP2 (TYP2_TYP1ID,TYP2_CODE,TYP2_DESC, TYP2_ORDER)
				VALUES (@TYP_ROWID, @TYP2_CODE, @TYP2_DESC, 1)
			END
		ELSE

			BEGIN
					IF NOT EXISTS (SELECT 1 FROM TYP WHERE TYP_ROWID = @TYP_ROWID)
						BEGIN 
							RAISERROR('Podany typ nie istnieje w systemie!',16,1)				
						END

						UPDATE TYP2
						set TYP2_CODE = @TYP2_CODE
						,TYP2_DESC = @TYP2_DESC
						where TYP2_ROWID =  @TYP2_ROWID
			END


	END
GO