SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SY_SET_SESSION_VARIABLE](@VARIABLE NVARCHAR(30), @VALUE nvarchar(4000))
AS
DECLARE @TMP_TABLE NVARCHAR(30)
DECLARE @SQL NVARCHAR(4000)
select @TMP_TABLE = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))
SELECT @SQL = N'IF EXISTS (SELECT NULL FROM '+@TMP_TABLE+' (NOLOCK) WHERE SES_OBJECT = '''+@VARIABLE+''' AND SES_CODE = '''+@VARIABLE+''')
  UPDATE '+@TMP_TABLE+' set ses_value = '''+@VALUE+''' WHERE SES_OBJECT = '''+@VARIABLE+''' AND SES_CODE = '''+@VARIABLE+'''
ELSE 
  INSERT INTO '+@TMP_TABLE+'(SES_OBJECT,SES_CODE,SES_VALUE) VALUES ('''+@VARIABLE+''', '''+@VARIABLE+''', '''+@VALUE+''')
'
EXEC sp_executesql @SQL
GO