SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[VS_LangMsgs_GetObjectTypes](
    @_USERID_ nvarchar(30) = null
)
WITH ENCRYPTION
AS

    (SELECT
        ObjectType
    FROM VS_LangMsgs
	GROUP BY ObjectType)	
	UNION SELECT 'FIELD' UNION SELECT 'FORM' UNION SELECT 'HELP' UNION SELECT 'MENU' UNION SELECT 'MSG' UNION SELECT 'TAB' UNION SELECT 'SECTIONS'
	
GO