SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SY_GET_SESSION_VARIABLE](@VARIABLE NVARCHAR(30), @VALUE NVARCHAR(4000) OUTPUT)
AS
DECLARE @TMP_TABLE NVARCHAR(30)
DECLARE @SQL NVARCHAR(4000)
select @TMP_TABLE = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))
SELECT @SQL = N'SELECT @RET = isnull(SES_VALUE,'''') FROM '+@TMP_TABLE+' WHERE SES_OBJECT = '''+@VARIABLE+''' AND SES_CODE = '''+@VARIABLE+''''
EXEC sp_executesql @SQL,N'@RET NVARCHAR(4000) OUTPUT',@RET=@VALUE OUTPUT
GO