SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SY_ISSET_SESSION_VARIABLE]
AS  
DECLARE @TMP_TABLE NVARCHAR(30) ,@RET int 
DECLARE @SQL NVARCHAR(4000)  
select @TMP_TABLE = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))  
SELECT @SQL = N'IF EXISTS (SELECT NULL FROM sys.objects where NAME = '''+@TMP_TABLE+''')
  SELECT @RET_OUT = 1  
ELSE   
  SELECT @RET_OUT = 0 
'  
EXEC sp_executesql @SQL,N'@RET_OUT int output',@RET_OUT=@RET
return @RET
GO