SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SY_SET_SESSION_MESSAGE](@MESSAGE NVARCHAR(4000))
AS
DECLARE @TMP_TABLE NVARCHAR(30)
DECLARE @SQL NVARCHAR(4000)
select @TMP_TABLE = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))
SELECT @SQL = N'IF EXISTS (SELECT NULL FROM TEMPDB.SYS.TABLES (NOLOCK) WHERE NAME = '''+@tmp_table+''') 
INSERT INTO '+@TMP_TABLE+'(SES_OBJECT,SES_CODE,SES_VALUE) VALUES (''MSG'',''MSG'','''+@MESSAGE+''')'
EXEC sp_executesql @SQL
GO