SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[VS_Forms_Search](
    @FormID nvarchar(50),
    @QueryStringGridFieldID nvarchar(250),
    @QueryStringFieldID nvarchar(250),
    @QueryStringFieldUserID nvarchar(250),
    @Title nvarchar(500),
    @SQLSelect nvarchar(max),
    @SQLProc nvarchar(max),
    @SQLGridSelect nvarchar(max),
    @SQLUpdate nvarchar(max),
    @SQLDelete nvarchar(max),
    @IsVirtualTable bit,
    @InDebug bit,
    @ShowSaveButton bit,
    @ShowDeleteButton bit,
    @ShowNewButton bit,
    @PopupReturn nvarchar(200),
    @GridHeight int,
    @GridWidth int,
    @EditAreaWidth int,
    @EditAreaHeight int,
    @GridHeaderHeight int,
    @ShowGrid bit,
    @ShowTree bit,
    @RefreshGridAfterBtnClick bit,
	  @ShowVerticalTree bit,
	  @ExpandTree bit,
    @GTAutoSize bit,
    @TableName nvarchar(250),
    @TablePrefix nvarchar(10),
    @SQLTreeSelect nvarchar(max),
    @AllowExcelExport bit,
    @ButtonTextNew nvarchar(150),
    @ButtonTextDelete nvarchar(150),
    @ButtonTextSave nvarchar(150),
    @FieldTreeDescription nvarchar(150),
    @FieldTreeID nvarchar(150),
    @FieldTreeParentID nvarchar(150),
    @FormDescription nvarchar(150),
    @NoOverrideDefaulByLink bit,
    @PreLoadDefault nvarchar(max),
    @AdminWhere nvarchar(50),
    @UserWhere nvarchar(50),
    @PageSize int,
    @AllowSorting bit,
    @AllowPagging bit,
    @ShowFilter bit,
    @AddWhere nvarchar(2000),
    @RegisterVariable nvarchar(2000),
    @UpdateObject nvarchar(50),
    @UserID nvarchar(30),
    @LangID nvarchar(10),
    @ShowDataSpy bit,
    @AltSavePrompt nvarchar(100),
    @AltRequirePrompt nvarchar(100),
    @AltRecCountPrompt nvarchar(100),
	@AltPageOfCounter nvarchar(100),	
    @DisableSGWhere bit,
    @DisableSOWhere bit,
    @ObjType nvarchar(10),
    @ShowTLine bit,
    @TLGroupWidth int,
    @RowHeight int,
    @RemHTMLTag bit,
    @MultiSelect bit,
    @AddNewIfEmpty bit,
    @StartupCmd nvarchar(400),
    @NoSOAW bit,
    @NoSSAW bit,
    @AllowQuickFilter bit,
    @ClearQuickFilter bit,
    @TreeWidth int,
    @TreeHeight int,
    @CustOrder nvarchar(150),
    @TreeNullValue nvarchar(50),
    @LGT bit,
    @pHeight int,
    @pWidth int,
	@Child nvarchar(50),
    @DBTab int,
    @ShowHelp nvarchar(30),
	@ShowHelpPdf nvarchar(30),
    @QSVariable nvarchar(2000),
    @HideErr bit,
    @SectionName nvarchar(1000),
    @GroupID nvarchar(20) = null,
    @_USERID_ varchar(20) = null,
    @AutoPageOff bit = null,
    @p1 nvarchar(4000) = null,
    @p2 nvarchar(50) = null,
    @b1 bit = null,
    @b2 bit = null,
    @ToTrans bit = null,
    @HideTitle bit = null,
    @DefFField nvarchar(50) = null,
    @DynamicTitle bit = null,
    @AllowEditGrid bit = null,
    @EditDataspy bit = null,
    @Customize bit = null,
    @CondFormatGrid nvarchar(4000) = null,
    @TryCatchSQL bit = null,
    @EnableSystemTran bit = null,
	  @MultiOrg bit = null,
	  @ShowCal bit = null,
	  @CalHeight int = null,
	  @CalWidth int = null,
	  @CalShowEventStartTime bit = null,
	  @CalShowEventEndTime bit = null,
	  @CalShowWeekend bit = null,
	  @CalStartDateField varchar(255) = null,
	  @CalEndDateField varchar(255) = null,
	  @CalEventNameField varchar(255) = null,
	  @CalEventDescField varchar(255) = null,
	  @CalEventIDField varchar(255) = null,
	  @SQLSelectCal varchar(4000) = null,
	  @CalTypeField varchar(255) = null,
	  @CalBGColorField varchar(255) = null,
	  @CalCheck bit = null,
	  @CalMove bit = null,
	  @CalPrint bit =null,
	  @CalSQLFD varchar(255) = null,
	  @CalMType varchar(255) = null,
	  @CalMoveSQL varchar(4000) = null,
	  @MultiSelectRefresh bit,
	  @RdlSchemaId nvarchar(30) = null,
		@CalGanttWMD int,
		@CalGanttWWD int,
		@CalGanttWDH int,
		@CalGanttWHQ int,
		@CalGanttDZ varchar(255) = null,
		@CalGanttDG INT =null,
		@CalGanttZ bit =null,
		@CalMonthNM int,
		@CalMonthNH int,
		@CalMonthH int,
		@CalGanttIDRes nvarchar(255),
		@CalGanttRes nvarchar(4000),
		@CalGanttStart nvarchar(255) = null,
		@CalGanttEnd nvarchar(255) = null,
		@CalGanttWMW int= null,
		@CalGanttResTT nvarchar(255)=null,
		@CalGanttDefX nvarchar(255) = null,
		@CalDAD bit=null,
		@CalGanttGroPar nvarchar(255)=null,
		@CalEvMovePB bit =null,
		@CalEvResizePB bit =null,
		@CalAResources nvarchar(4000)= null,
		@CalAId nvarchar(255)= null,
		@ShowGridColsConf bit = null,
		@ShowMultifilterButtons bit = NULL,
		@ShowGridSummary bit = NULL,
		@ExpandTreeToLevel bit = NULL,
		@ExpandTreeLevel int = NULL,
		@TurnQuickFilterOn bit = NULL,
		@WithoutPostbackOnQSC bit = NULL,
		@CheckIfDataWhereChanged bit = NULL,
		@AllowGridColumnReorder bit = NULL,
		@ShowErrorsInDialogBox bit = NULL,
		@GridEditMode nvarchar(30) = NULL,
		@UseContextMenu bit = NULL,
		@TruncGridContent bit = NULL,
		@ShowMultifilterClearButtons bit =NULL
)
WITH ENCRYPTION
AS

    SELECT
        FormID, QueryStringGridFieldID, QueryStringFieldID, QueryStringFieldUserID, Title,
        SQLSelect, SQLProc, SQLGridSelect, SQLUpdate, SQLDelete, IsVirtualTable,
        InDebug, ShowSaveButton, ShowDeleteButton, ShowNewButton, PopupReturn,
        GridHeight, GridWidth, EditAreaWidth, EditAreaHeight, GridHeaderHeight,
        ShowGrid, ShowTree, RefreshGridAfterBtnClick, ShowVerticalTree, ExpandTree, GTAutoSize, TableName, TablePrefix,
        SQLTreeSelect, AllowExcelExport, ButtonTextNew, ButtonTextDelete, ButtonTextSave,
        FieldTreeDescription, FieldTreeID, FieldTreeParentID, FormDescription, NoOverrideDefaulByLink,
        PreLoadDefault, AdminWhere, UserWhere, PageSize, AllowSorting,
        AllowPagging, ShowFilter, AddWhere, RegisterVariable, UpdateObject,
        UserID, LangID, ShowDataSpy, AltSavePrompt, AltRequirePrompt,
        AltRecCountPrompt, AltPageOfCounter, DisableSGWhere, DisableSOWhere, ObjType, ShowTLine,
        TLGroupWidth, RowHeight, RemHTMLTag, MultiSelect, AddNewIfEmpty,
        StartupCmd, NoSOAW, NoSSAW, AllowQuickFilter, ClearQuickFilter, TreeWidth,
        TreeHeight, CustOrder, TreeNullValue, LGT, pHeight,
        pWidth, Child, DBTab, ShowHelp, ShowHelpPdf, QSVariable,
        HideErr, SectionName, GroupID, AutoPageOff, p1,
        p2, b1, b2, ToTrans, HideTitle,
        DefFField, DynamicTitle, AllowEditGrid, EditDataspy, Customize,
		    CondFormatGrid, TryCatchSQL, EnableSystemTran, MultiOrg,
		    ShowCal,CalHeight,CalWidth,CalShowEventStartTime,CalShowEventEndTime,CalShowWeekend,
		    CalStartDateField,CalEndDateField,CalEventNameField,CalEventDescField,CalEventIDField,
		    SQLSelectCal,CalTypeField,CalBGColorField,CalCheck,CalMove,CalPrint,
		    CalSQLFD,CalMType,CalMoveSQL,MultiSelectRefresh, RdlSchemaId,CalGanttWMD,CalGanttWWD,CalGanttWDH,CalGanttWHQ,
		CalGanttDZ,CalGanttDG,CalGanttZ,CalMonthNM,CalMonthNH,CalMonthH,CalGanttIDRes,CalGanttRes,CalGanttStart,CalGanttEnd,CalGanttWMW,CalGanttResTT,
		CalGanttDefX,CalDAD,CalGanttGroPar,CalEvMovePB,CalEvResizePB,CalAResources,CalAId, ShowGridColsConf, ShowMultifilterButtons, '' as AddWhereSystemFilter,
		ShowGridSummary, ExpandTreeToLevel, ExpandTreeLevel, TurnQuickFilterOn, WithoutPostbackOnQSC, CheckIfDataWhereChanged,
		AllowGridColumnReorder, ShowErrorsInDialogBox, GridEditMode, UseContextMenu, TruncGridContent, ShowMultifilterClearButtons
    FROM VS_Forms
            /* WHERE QueryStringGridFieldID = @QueryStringGridFieldID AND QueryStringFieldID = @QueryStringFieldID AND QueryStringFieldUserID = @QueryStringFieldUserID AND Title = @Title AND SQLSelect = @SQLSelect AND
            SQLGridSelect = @SQLGridSelect AND SQLUpdate = @SQLUpdate AND SQLDelete = @SQLDelete AND IsVirtualTable = @IsVirtualTable AND InDebug = @InDebug AND
            ShowSaveButton = @ShowSaveButton AND ShowDeleteButton = @ShowDeleteButton AND ShowNewButton = @ShowNewButton AND PopupReturn = @PopupReturn AND GridHeight = @GridHeight AND
            GridWidth = @GridWidth AND EditAreaWidth = @EditAreaWidth AND EditAreaHeight = @EditAreaHeight AND GridHeaderHeight = @GridHeaderHeight AND ShowGrid = @ShowGrid AND
            ShowTree = @ShowTree AND GTAutoSize = @GTAutoSize AND TableName = @TableName AND TablePrefix = @TablePrefix AND SQLTreeSelect = @SQLTreeSelect AND
            AllowExcelExport = @AllowExcelExport AND ButtonTextNew = @ButtonTextNew AND ButtonTextDelete = @ButtonTextDelete AND ButtonTextSave = @ButtonTextSave AND FieldTreeDescription = @FieldTreeDescription AND
            FieldTreeID = @FieldTreeID AND FieldTreeParentID = @FieldTreeParentID AND FormDescription = @FormDescription AND NoOverrideDefaulByLink = @NoOverrideDefaulByLink AND PreLoadDefault = @PreLoadDefault AND
            AdminWhere = @AdminWhere AND UserWhere = @UserWhere AND PageSize = @PageSize AND AllowSorting = @AllowSorting AND AllowPagging = @AllowPagging AND
            ShowFilter = @ShowFilter AND AddWhere = @AddWhere AND RegisterVariable = @RegisterVariable AND UpdateObject = @UpdateObject AND UserID = @UserID AND
            LangID = @LangID AND ShowDataSpy = @ShowDataSpy AND AltSavePrompt = @AltSavePrompt AND AltRequirePrompt = @AltRequirePrompt AND AltRecCountPrompt = @AltRecCountPrompt AND AltPageOfCounter = @AltPageOfCounter AND 
            DisableSGWhere = @DisableSGWhere AND DisableSOWhere = @DisableSOWhere AND ObjType = @ObjType AND ShowTLine = @ShowTLine AND TLGroupWidth = @TLGroupWidth AND
            RowHeight = @RowHeight AND RemHTMLTag = @RemHTMLTag AND MultiSelect = @MultiSelect AND AddNewIfEmpty = @AddNewIfEmpty AND StartupCmd = @StartupCmd AND
            NoSOAW = @NoSOAW AND NoSSAW = @NoSSAW AND AllowQuickFilter = @AllowQuickFilter AND TreeWidth = @TreeWidth AND TreeHeight = @TreeHeight AND
            CustOrder = @CustOrder AND TreeNullValue = @TreeNullValue AND LGT = @LGT AND pHeight = @pHeight AND pWidth = @pWidth AND
			Child = @Child AND DBTab = @DBTab AND ShowHelp = @ShowHelp AND QSVariable = @QSVariable AND HideErr = @HideErr AND
			SectionName = @SectionName AND GroupID = @GroupID AND AutoPageOff = @AutoPageOff AND p1 = @p1 AND p2 = @p2 AND
            b1 = @b1 AND b2 = @b2 AND ToTrans = @ToTrans AND HideTitle = @HideTitle AND DefFField = @DefFField AND
            DynamicTitle = @DynamicTitle AND AllowEditGrid = @AllowEditGrid AND EditDataspy = @EditDataspy AND Customize = @Customize AND CondFormatGrid = @CondFormatGrid AND
            TryCatchSQL = @TryCatchSQL AND EnableSystemTran = @EnableSystemTran /*  AND _USERID_ = @_USERID_ */ */
GO