SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROC [dbo].[ZMT_REMAINING_MAIL_PROC]
AS
BEGIN


	/*WYSYŁKA MAILI DLA FORMULARZY RUCHU W STATUSIE POTWIERDZONE WYDANIE, GDZUE SPRZET PRZEBYWA W SERWISIE 7 DNI*/
	
	EXEC SP_REQUEST_MAILSENT_PROC

	/*WYSYŁKA POWIADOMIENIA MAILOWEGO W PRZYPADKU, GDY DOKUMENT OCZEKUJE DŁUŻEJ NIŻ TRZY DNI NA REAKCJĘ UŻYTKOWNIKA*/
	EXEC dbo.THREE_DAYS_DELAY_MAIL NULL

END
GO