SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SY_SET_SESSION_TABLE]
AS
DECLARE @TMP_TABLE NVARCHAR(30)
DECLARE @SQL NVARCHAR(4000)

select @TMP_TABLE = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))
SELECT @SQL = N'IF NOT EXISTS (SELECT NULL FROM TEMPDB.SYS.TABLES (NOLOCK) WHERE NAME = '''+@tmp_table+''') 
CREATE TABLE ' + @TMP_TABLE + '(SES_SQLIDENTITY INT IDENTITY(1,1) NOT NULL, SES_OBJECT NVARCHAR(30) NOT NULL, SES_CODE NVARCHAR(30) NOT NULL, SES_VALUE NVARCHAR(4000) NULL)'
EXEC sp_executesql @SQL
GO