SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SY_GET_SESSION_MESSAGE] @P_ERRORTEXT NVARCHAR(4000) OUTPUT
AS
declare @tmp_table nvarchar(30)
DECLARE @SQL NVARCHAR(4000)

select @tmp_table = '##VS_SESSION_'+CAST(@@SPID as nvarchar(30))
SELECT @P_ERRORTEXT = ''
SELECT @SQL = N'IF EXISTS (SELECT NULL FROM TEMPDB.SYS.TABLES (NOLOCK) WHERE NAME = '''+@tmp_table+''') SELECT @MSG_OUT = @MSG_OUT + SES_VALUE FROM '+@tmp_table+' (NOLOCK) WHERE SES_OBJECT = ''MSG'''

EXEC sp_executesql @SQL,N'@MSG_OUT NVARCHAR(4000) OUTPUT',@MSG_OUT=@P_ERRORTEXT OUTPUT

GO