SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[VS_Forms_Update](
    @FormID nvarchar(50) OUT,
    @QueryStringGridFieldID nvarchar(250),
    @QueryStringFieldID nvarchar(250),
    @QueryStringFieldUserID nvarchar(250),
    @Title nvarchar(500),
    @SQLSelect nvarchar(max),
    @SQLProc nvarchar(max),
    @SQLGridSelect nvarchar(max),
    @SQLUpdate nvarchar(max),
    @SQLDelete nvarchar(max),
    @IsVirtualTable bit,
    @InDebug bit,
    @ShowSaveButton bit,
    @ShowDeleteButton bit,
    @ShowNewButton bit,
    @PopupReturn nvarchar(200),
    @GridHeight int,
    @GridWidth int,
    @EditAreaWidth int,
    @EditAreaHeight int,
    @GridHeaderHeight int,
    @ShowGrid bit,
    @ShowTree bit,
	@RefreshGridAfterBtnClick bit,
	@ShowVerticalTree bit,
	@ExpandTree bit,
    @GTAutoSize bit,
    @TableName nvarchar(250),
    @TablePrefix nvarchar(10),
    @SQLTreeSelect nvarchar(max),
    @AllowExcelExport bit,
    @ButtonTextNew nvarchar(150),
    @ButtonTextDelete nvarchar(150),
    @ButtonTextSave nvarchar(150),
    @FieldTreeDescription nvarchar(150),
    @FieldTreeID nvarchar(150),
    @FieldTreeParentID nvarchar(150),
    @FormDescription nvarchar(150),
    @NoOverrideDefaulByLink bit,
    @PreLoadDefault nvarchar(max),
    @AdminWhere nvarchar(50),
    @UserWhere nvarchar(50),
    @PageSize int,
    @AllowSorting bit,
    @AllowPagging bit,
    @ShowFilter bit,
    @AddWhere nvarchar(2000),
    @RegisterVariable nvarchar(2000),
    @UpdateObject nvarchar(50),
    @UserID nvarchar(30),
    @LangID nvarchar(10),
    @ShowDataSpy bit,
    @AltSavePrompt nvarchar(100),
    @AltRequirePrompt nvarchar(100),
    @AltRecCountPrompt nvarchar(100),
	@AltPageOfCounter nvarchar(100),	
    @DisableSGWhere bit,
    @DisableSOWhere bit,
    @ObjType nvarchar(10),
    @ShowTLine bit,
    @TLGroupWidth int,
    @RowHeight int,
    @RemHTMLTag bit,
    @MultiSelect bit,
    @AddNewIfEmpty bit,
    @StartupCmd nvarchar(400),
    @NoSOAW bit,
    @NoSSAW bit,
    @AllowQuickFilter bit,
    @ClearQuickFilter bit,
    @TreeWidth int,
    @TreeHeight int,
    @CustOrder nvarchar(150),
    @TreeNullValue nvarchar(50),
    @LGT bit,
    @pHeight int,
    @pWidth int,
	@Child nvarchar(50),
    @DBTab int,
    @ShowHelp nvarchar(30),
	@ShowHelpPdf nvarchar(30),
    @QSVariable nvarchar(2000),
    @HideErr bit,
    @SectionName nvarchar(1000),
    @GroupID nvarchar(20) = null,
    @AutoPageOff bit = null,
    @p1 nvarchar(4000) = null,
    @p2 nvarchar(50) = null,
    @b1 bit = null,
    @b2 bit = null,
    @ToTrans bit = null,
    @HideTitle bit = null,
    @DefFField nvarchar(50) = null,
    @DynamicTitle bit = null,
    @AllowEditGrid bit = null,
    @EditDataspy bit = null,
    @Customize bit = null,
    @CondFormatGrid nvarchar(4000) = null,
    @TryCatchSQL bit = null,
    @EnableSystemTran bit = null,
	@MultiOrg bit = null,
	@ShowCal bit = null,
	@CalHeight int = null,
	@CalWidth int = null,
	@CalShowEventStartTime bit = null,
	@CalShowEventEndTime bit = null,
	@CalShowWeekend bit = null,
	@CalStartDateField varchar(255) = null,
	@CalEndDateField varchar(255) = null,
	@CalEventNameField varchar(255) = null,
	@CalEventDescField varchar(255) = null,
	@CalEventIDField varchar(255) = null,
	@SQLSelectCal varchar(4000) = null,
	@CalTypeField varchar(255) = null,
	@CalBGColorField varchar(255) = null,
	@CalCheck bit = null,
	@CalMove bit = null,
	@CalPrint bit =null,

	@CalGanttWMD int= null,
	@CalGanttWWD int= null,
	@CalGanttWDH int= null,
	@CalGanttWHQ int= null,
	@CalGanttDZ varchar(255) = null,
	@CalGanttDG INT =null,
	@CalGanttZ bit =null,
	@CalMonthNM int= null,
	@CalMonthNH int= null,
	@CalMonthH int= null,
    @CalGanttIDRes nvarchar(255)= null,
    @CalGanttRes nvarchar(4000)= null,
	@CalGanttStart nvarchar(255) = null,
	@CalGanttEnd nvarchar(255) = null,
	@CalGanttWMW int= null,
	@CalGanttResTT nvarchar(255)=null,
	@CalGanttDefX nvarchar(255) = null,
	@CalDAD bit=null,
	@CalGanttGroPar nvarchar(255)=null,
	@CalEvMovePB bit =null,
	@CalEvResizePB bit =null,
	@CalAResources nvarchar(4000)= null,
	@CalAId nvarchar(255)= null,
		
	@LinkToTree bit = null,
	@CalSQLFD varchar(255) = null,
	@CalMType varchar(255) = null,
	@CalMoveSQL varchar(4000) = null,
	@MultiSelectRefresh bit,
	@RdlSchemaId nvarchar(30) = null,
	@ShowGridColsConf bit = null,
	@ShowMultifilterButtons bit = NULL,
	@ShowGridSummary bit = NULL,
	@ExpandTreeToLevel bit = NULL,
	@ExpandTreeLevel int = NULL,
	@TurnQuickFilterOn bit = NULL,
	@WithoutPostbackOnQSC bit = NULL,
	@CheckIfDataWhereChanged bit = NULL,
	@AllowGridColumnReorder bit = NULL,
	@ShowErrorsInDialogBox bit = NULL,
	@GridEditMode nvarchar(10) = NULL,
	@UseContextMenu bit = NULL,
	@TruncGridContent bit = NULL,
	@ShowMultifilterClearButtons bit = NULL
)
WITH ENCRYPTION
AS

IF @FormID is null
    SET @FormID = NewID()
IF @FormID =''
    SET @FormID = NewID()

IF NOT EXISTS (SELECT * FROM VS_Forms WHERE FormID = @FormID)
BEGIN
    INSERT INTO VS_Forms(
        FormID, QueryStringGridFieldID, QueryStringFieldID, QueryStringFieldUserID, Title,
        SQLSelect, SQLProc, SQLGridSelect, SQLUpdate, SQLDelete, IsVirtualTable,
        InDebug, ShowSaveButton, ShowDeleteButton, ShowNewButton, PopupReturn,
        GridHeight, GridWidth, EditAreaWidth, EditAreaHeight, GridHeaderHeight,
        ShowGrid, ShowTree, RefreshGridAfterBtnClick, ShowVerticalTree, ExpandTree, GTAutoSize, TableName, TablePrefix,
        SQLTreeSelect, AllowExcelExport, ButtonTextNew, ButtonTextDelete, ButtonTextSave,
        FieldTreeDescription, FieldTreeID, FieldTreeParentID, FormDescription, NoOverrideDefaulByLink,
        PreLoadDefault, AdminWhere, UserWhere, PageSize, AllowSorting,
        AllowPagging, ShowFilter, AddWhere, RegisterVariable, UpdateObject,
        UserID, LangID, ShowDataSpy, AltSavePrompt, AltRequirePrompt,
        AltRecCountPrompt, AltPageOfCounter, DisableSGWhere, DisableSOWhere, ObjType, ShowTLine,
        TLGroupWidth, RowHeight, RemHTMLTag, MultiSelect, AddNewIfEmpty,
        StartupCmd, NoSOAW, NoSSAW, AllowQuickFilter, ClearQuickFilter, TreeWidth,
        TreeHeight, CustOrder, TreeNullValue, LGT, pHeight,
        pWidth, Child, DBTab, ShowHelp, ShowHelpPdf, QSVariable,
        HideErr, SectionName, GroupID, AutoPageOff, p1,
        p2, b1, b2, ToTrans, HideTitle,
        DefFField, DynamicTitle, AllowEditGrid, EditDataspy, Customize,
        CondFormatGrid, TryCatchSQL, EnableSystemTran, MultiOrg,ShowCal,CalHeight,CalWidth,CalShowEventStartTime,
        CalShowEventEndTime,CalShowWeekend,CalStartDateField,CalEndDateField,CalEventNameField,CalEventDescField,
        CalEventIDField,SQLSelectCal,CalTypeField,CalBGColorField,CalCheck,CalMove,CalPrint,CalSQLFD,
		CalMType,CalMoveSQL, MultiSelectRefresh, RdlSchemaId,CalGanttWMD,CalGanttWWD,CalGanttWDH,CalGanttWHQ,
		CalGanttDZ,CalGanttDG,CalGanttZ,CalMonthNM,CalMonthNH,CalMonthH,CalGanttIDRes,CalGanttRes,CalGanttStart,
		CalGanttEnd,CalGanttWMW,CalGanttResTT,CalGanttDefX,CalDAD,CalGanttGroPar,CalEvMovePB,CalEvResizePB,CalAResources,
		CalAId,  ShowGridColsConf, ShowMultifilterButtons, ShowGridSummary, ExpandTreeToLevel, ExpandTreeLevel, TurnQuickFilterOn, 
		WithoutPostbackOnQSC, CheckIfDataWhereChanged, AllowGridColumnReorder, ShowErrorsInDialogBox, GridEditMode, UseContextMenu,
		TruncGridContent, ShowMultifilterClearButtons)
    VALUES (
        @FormID, @QueryStringGridFieldID, @QueryStringFieldID, @QueryStringFieldUserID, @Title,
        @SQLSelect, @SQLProc, @SQLGridSelect, @SQLUpdate, @SQLDelete, @IsVirtualTable,
        @InDebug, @ShowSaveButton, @ShowDeleteButton, @ShowNewButton, @PopupReturn,
        @GridHeight, @GridWidth, @EditAreaWidth, @EditAreaHeight, @GridHeaderHeight,
        @ShowGrid, @ShowTree, @RefreshGridAfterBtnClick, @ShowVerticalTree, @ExpandTree, @GTAutoSize, @TableName, @TablePrefix,
        @SQLTreeSelect, @AllowExcelExport, @ButtonTextNew, @ButtonTextDelete, @ButtonTextSave,
        @FieldTreeDescription, @FieldTreeID, @FieldTreeParentID, @FormDescription, @NoOverrideDefaulByLink,
        @PreLoadDefault, @AdminWhere, @UserWhere, @PageSize, @AllowSorting,
        @AllowPagging, @ShowFilter, @AddWhere, @RegisterVariable, @UpdateObject,
        @UserID, @LangID, @ShowDataSpy, @AltSavePrompt, @AltRequirePrompt,
        @AltRecCountPrompt, @AltPageOfCounter, @DisableSGWhere, @DisableSOWhere, @ObjType, @ShowTLine,
        @TLGroupWidth, @RowHeight, @RemHTMLTag, @MultiSelect, @AddNewIfEmpty,
        @StartupCmd, @NoSOAW, @NoSSAW, @AllowQuickFilter, @ClearQuickFilter, @TreeWidth,
        @TreeHeight, @CustOrder, @TreeNullValue, @LGT, @pHeight,
        @pWidth, @Child, @DBTab, @ShowHelp, @ShowHelpPdf, @QSVariable,
        @HideErr, @SectionName, @GroupID, @AutoPageOff, @p1,
        @p2, @b1, @b2, @ToTrans, @HideTitle,
        @DefFField, @DynamicTitle, @AllowEditGrid, @EditDataspy, @Customize,
        @CondFormatGrid, @TryCatchSQL, @EnableSystemTran, @MultiOrg,
		@ShowCal,@CalHeight,@CalWidth,@CalShowEventStartTime,@CalShowEventEndTime,@CalShowWeekend,
		@CalStartDateField,@CalEndDateField,@CalEventNameField,@CalEventDescField,@CalEventIDField,
		@SQLSelectCal,@CalTypeField,@CalBGColorField,@CalCheck,@CalMove,@CalPrint,@CalSQLFD,@CalMType,@CalMoveSQL, 
		@MultiSelectRefresh, @RdlSchemaId,@CalGanttWMD, @CalGanttWWD,@CalGanttWDH,@CalGanttWHQ,@CalGanttDZ,@CalGanttDG,
		@CalGanttZ,@CalMonthNM,@CalMonthNH,@CalMonthH,@CalGanttIDRes,@CalGanttRes,@CalGanttStart,
		@CalGanttEnd,@CalGanttWMW,@CalGanttResTT,@CalGanttDefX,@CalDAD,@CalGanttGroPar,@CalEvMovePB,
		@CalEvResizePB,@CalAResources,@CalAId, @ShowGridColsConf, @ShowMultifilterButtons, @ShowGridSummary,
		@ExpandTreeToLevel, @ExpandTreeLevel, @TurnQuickFilterOn, @WithoutPostbackOnQSC, @CheckIfDataWhereChanged,
		@AllowGridColumnReorder, @ShowErrorsInDialogBox, @GridEditMode, @UseContextMenu,
		@TruncGridContent,@ShowMultifilterClearButtons)
END
ELSE
BEGIN
    UPDATE VS_Forms SET
        QueryStringGridFieldID = @QueryStringGridFieldID, QueryStringFieldID = @QueryStringFieldID, QueryStringFieldUserID = @QueryStringFieldUserID, 
        Title = @Title, SQLSelect = @SQLSelect, SQLProc = @SQLProc, SQLGridSelect = @SQLGridSelect, SQLUpdate = @SQLUpdate, SQLDelete = @SQLDelete, 
        IsVirtualTable = @IsVirtualTable, InDebug = @InDebug, ShowSaveButton = @ShowSaveButton, ShowDeleteButton = @ShowDeleteButton, ShowNewButton = @ShowNewButton, 
        PopupReturn = @PopupReturn, GridHeight = @GridHeight, GridWidth = @GridWidth, EditAreaWidth = @EditAreaWidth, EditAreaHeight = @EditAreaHeight, 
        GridHeaderHeight = @GridHeaderHeight, ShowGrid = @ShowGrid, ShowTree = @ShowTree, RefreshGridAfterBtnClick = @RefreshGridAfterBtnClick, 
        ShowVerticalTree = @ShowVerticalTree, ExpandTree = @ExpandTree, GTAutoSize = @GTAutoSize, TableName = @TableName, TablePrefix = @TablePrefix, 
        SQLTreeSelect = @SQLTreeSelect, AllowExcelExport = @AllowExcelExport, ButtonTextNew = @ButtonTextNew, ButtonTextDelete = @ButtonTextDelete, 
        ButtonTextSave = @ButtonTextSave, FieldTreeDescription = @FieldTreeDescription, FieldTreeID = @FieldTreeID, FieldTreeParentID = @FieldTreeParentID, 
        FormDescription = @FormDescription, NoOverrideDefaulByLink = @NoOverrideDefaulByLink, PreLoadDefault = @PreLoadDefault, AdminWhere = @AdminWhere, 
        UserWhere = @UserWhere, PageSize = @PageSize, AllowSorting = @AllowSorting, AllowPagging = @AllowPagging, ShowFilter = @ShowFilter, AddWhere = @AddWhere, 
        RegisterVariable = @RegisterVariable, UpdateObject = @UpdateObject, UserID = @UserID, LangID = @LangID, ShowDataSpy = @ShowDataSpy, AltSavePrompt = @AltSavePrompt, 
        AltRequirePrompt = @AltRequirePrompt, AltRecCountPrompt = @AltRecCountPrompt, AltPageOfCounter = @AltPageOfCounter, DisableSGWhere = @DisableSGWhere, DisableSOWhere = @DisableSOWhere, 
        ObjType = @ObjType, ShowTLine = @ShowTLine, TLGroupWidth = @TLGroupWidth, RowHeight = @RowHeight, RemHTMLTag = @RemHTMLTag, MultiSelect = @MultiSelect, 
        AddNewIfEmpty = @AddNewIfEmpty, StartupCmd = @StartupCmd, NoSOAW = @NoSOAW, NoSSAW = @NoSSAW, AllowQuickFilter = @AllowQuickFilter, 
        ClearQuickFilter = @ClearQuickFilter, TreeWidth = @TreeWidth, TreeHeight = @TreeHeight, CustOrder = @CustOrder, TreeNullValue = @TreeNullValue, 
        LGT = @LGT, pHeight = @pHeight, pWidth = @pWidth, Child = @Child, DBTab = @DBTab, ShowHelp = @ShowHelp, ShowHelpPdf = @ShowHelpPdf, 
        QSVariable = @QSVariable, HideErr = @HideErr, SectionName = @SectionName, GroupID = @GroupID, AutoPageOff = @AutoPageOff, p1 = @p1, p2 = @p2,
        b1 = @b1, b2 = @b2, ToTrans = @ToTrans, HideTitle = @HideTitle, DefFField = @DefFField, DynamicTitle = @DynamicTitle, AllowEditGrid = @AllowEditGrid, 
        EditDataspy = @EditDataspy, Customize = @Customize, CondFormatGrid = @CondFormatGrid, TryCatchSQL = @TryCatchSQL, EnableSystemTran = @EnableSystemTran, 
        MultiOrg = @MultiOrg, ShowCal=@ShowCal,CalHeight=@CalHeight,CalWidth=@CalWidth,CalShowEventStartTime=@CalShowEventStartTime,
		CalShowEventEndTime=@CalShowEventEndTime,CalShowWeekend=@CalShowWeekend, CalStartDateField=@CalStartDateField,CalEndDateField=@CalEndDateField,
		CalEventNameField=@CalEventNameField,CalEventDescField=@CalEventDescField,CalEventIDField=@CalEventIDField, SQLSelectCal=@SQLSelectCal,
		CalTypeField=@CalTypeField,CalBGColorField=@CalBGColorField,CalCheck=@CalCheck,CalMove=@CalMove,CalPrint=@CalPrint, CalSQLFD=@CalSQLFD,
		CalMType=@CalMType,CalMoveSQL=@CalMoveSQL,MultiSelectRefresh=@MultiSelectRefresh, RdlSchemaId=@RdlSchemaId,CalGanttWMD=@CalGanttWMD,
		CalGanttWWD=@CalGanttWWD,CalGanttWDH=@CalGanttWDH,CalGanttWHQ=@CalGanttWHQ,CalGanttDZ=@CalGanttDZ,CalGanttDG=@CalGanttDG, CalGanttZ=@CalGanttZ,
		CalMonthNM=@CalMonthNM,CalMonthNH=@CalMonthNH,CalMonthH=@CalMonthH,CalGanttIDRes=@CalGanttIDRes,CalGanttRes=@CalGanttRes,CalGanttStart=@CalGanttStart,
		CalGanttEnd=@CalGanttEnd,CalGanttWMW=@CalGanttWMW,CalGanttResTT=@CalGanttResTT, CalGanttDefX=@CalGanttDefX,CalDAD=@CalDAD,CalGanttGroPar=@CalGanttGroPar,
		CalEvMovePB=@CalEvMovePB,CalEvResizePB=@CalEvResizePB,CalAResources=@CalAResources,CalAId=@CalAId, ShowGridColsConf = @ShowGridColsConf, 
		ShowMultifilterButtons = @ShowMultifilterButtons, ShowGridSummary = @ShowGridSummary, ExpandTreeToLevel = @ExpandTreeToLevel, 
		ExpandTreeLevel = @ExpandTreeLevel, TurnQuickFilterOn = @TurnQuickFilterOn, WithoutPostbackOnQSC = @WithoutPostbackOnQSC, 
		CheckIfDataWhereChanged = @CheckIfDataWhereChanged, AllowGridColumnReorder = @AllowGridColumnReorder, ShowErrorsInDialogBox = @ShowErrorsInDialogBox,
	    GridEditMode = @GridEditMode, UseContextMenu = @UseContextMenu, TruncGridContent = @TruncGridContent, ShowMultifilterClearButtons = @ShowMultifilterClearButtons
        WHERE FormID = @FormID
END
GO