SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
create FUNCTION [dbo].[GetNums](@n AS BIGINT) RETURNS TABLE  
AS  
RETURN  
WITH  
L0 AS(SELECT 1 AS c UNION ALL SELECT 1),  
L1 AS(SELECT 1 AS c FROM L0 AS A, L0 AS B),  
L2 AS(SELECT 1 AS c FROM L1 AS A, L1 AS B),  
L3 AS(SELECT 1 AS c FROM L2 AS A, L2 AS B),  
L4 AS(SELECT 1 AS c FROM L3 AS A, L3 AS B),  
L5 AS(SELECT 1 AS c FROM L4 AS A, L4 AS B)  
SELECT TOP (@n) ROW_NUMBER() OVER(ORDER BY (SELECT 0)) AS n FROM L5;  
GO