SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[STENCIL_STRUCTURE] (@sts_rowid int)
RETURNS TABLE
AS
RETURN
select NULL as TPARENT, STS_ROWID AS TCHILD, STS_DESC as [TDESCRIPTION] from dbo.STENCIL WHERE STS_ROWID = @sts_rowid

UNION ALL 

SELECT STL_PARENTID AS PARENT, STL_CHILDID AS CHILD, (SELECT STS_DESC FROM STENCIL WHERE STS_ROWID = STL_CHILDID ) AS [DESCRIPTION] from dbo.STENCILLN WHERE  STL_PARENTID =   @sts_rowid 

GO