SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE FUNCTION [dbo].[PROPERTIES_STS_LISTv] (@p_ASP_PROID nvarchar(512))
RETURNS TABLE
AS
RETURN
select PRL_TEXT from dbo.PROPERTIES_LIST where PRL_PROID = @p_ASP_PROID
	



GO