CREATE TABLE [dbo].[OBJTECHPROT] (
  [POT_ROWID] [int] IDENTITY,
  [POT_CODE] [nvarchar](30) NOT NULL,
  [POT_ORG] [nvarchar](30) NOT NULL,
  [POT_DESC] [nvarchar](80) NULL,
  [POT_NOTE] [ntext] NULL,
  [POT_DATE] [datetime] NULL,
  [POT_STATUS] [nvarchar](30) NULL,
  [POT_TYPE] [nvarchar](30) NULL,
  [POT_TYPE2] [nvarchar](30) NULL,
  [POT_TYPE3] [nvarchar](30) NULL,
  [POT_RSTATUS] [int] NULL CONSTRAINT [DF_OBJTECHPROT_POT_RSTATUS] DEFAULT (0),
  [POT_CREUSER] [nvarchar](30) NULL CONSTRAINT [DF_OBJTECHPROT_POT_CREUSER] DEFAULT ('SA'),
  [POT_CREDATE] [datetime] NULL CONSTRAINT [DF_OBJTECHPROT_CREDATE] DEFAULT (getdate()),
  [POT_UPDUSER] [nvarchar](30) NULL,
  [POT_UPDDATE] [datetime] NULL,
  [POT_NOTUSED] [int] NULL CONSTRAINT [DF_OBJTECHPROT_POT_NOTUSED] DEFAULT (0),
  [POT_ID] [nvarchar](50) NULL CONSTRAINT [DF_OBJTECHPROT_ID] DEFAULT (CONVERT([nvarchar](50),newid(),(0))),
  [POT_TXT01] [nvarchar](30) NULL,
  [POT_TXT02] [nvarchar](30) NULL,
  [POT_TXT03] [nvarchar](30) NULL,
  [POT_TXT04] [nvarchar](30) NULL,
  [POT_TXT05] [nvarchar](30) NULL,
  [POT_TXT06] [nvarchar](80) NULL,
  [POT_TXT07] [nvarchar](80) NULL,
  [POT_TXT08] [nvarchar](255) NULL,
  [POT_TXT09] [nvarchar](255) NULL,
  [POT_NTX01] [numeric](24, 6) NULL,
  [POT_NTX02] [numeric](24, 6) NULL,
  [POT_NTX03] [numeric](24, 6) NULL,
  [POT_NTX04] [numeric](24, 6) NULL,
  [POT_NTX05] [numeric](24, 6) NULL,
  [POT_COM01] [ntext] NULL,
  [POT_COM02] [ntext] NULL,
  [POT_DTX01] [datetime] NULL,
  [POT_DTX02] [datetime] NULL,
  [POT_DTX03] [datetime] NULL,
  [POT_DTX04] [datetime] NULL,
  [POT_DTX05] [datetime] NULL,
  [POT_STNID] [int] NULL,
  [CHK_GU_DZR] [int] NULL,
  [CHK_GU_IT] [int] NULL,
  [CHK_GU_RKB] [int] NULL,
  [CHK_GU_UR] [int] NULL,
  [POT_UZASADNIENIE] [nvarchar](70) NULL,
  [POT_UCHWALA_OPIS] [nvarchar](70) NULL,
  [POT_CZY_UCHWALA] [nvarchar](1) NULL,
  [POT_CZY_DECYZJA] [nvarchar](1) NULL,
  [POT_DECYZJA_OPIS] [nvarchar](70) NULL,
  [POT_CZY_ZAKRES] [nvarchar](1) NULL,
  [POT_ZAKRES_OPIS] [nvarchar](70) NULL,
  [POT_OCENA_OPIS] [nvarchar](70) NULL,
  [POT_CZY_OCENA] [nvarchar](1) NULL,
  [POT_CZY_EKSPERTYZY] [nvarchar](1) NULL,
  [POT_EKSPERTYZY_OPIS] [nvarchar](70) NULL,
  [POT_SPOSOBLIKW] [nvarchar](35) NULL,
  [POT_PSP_POSKI] [nvarchar](30) NULL,
  [POT_MIESIAC] [int] NULL,
  [CHK_GU_DZR_USER] [nvarchar](30) NULL,
  [CHK_GU_IT_USER] [nvarchar](30) NULL,
  [CHK_GU_RKB_USER] [nvarchar](30) NULL,
  [CHK_GU_UR_USER] [nvarchar](30) NULL,
  [POT_KOMISJA] [nvarchar](max) NULL,
  [POT_MANAGER] [nvarchar](50) NULL,
  [POT_REALIZATOR] [nvarchar](50) NULL,
  [POT_ROK] [int] NULL,
  [CHK_GU_DZR_REJ] [int] NULL,
  [CHK_GU_IT_REJ] [int] NULL,
  [CHK_GU_RBK_REJ] [int] NULL,
  [CHK_GU_UR_REJ] [int] NULL,
  [POT_MODERN_PROFILE] [int] NULL,
  [POT_RETURN] [int] NULL,
  [POT_POTCLOSE_DATE] [datetime] NULL,
  CONSTRAINT [PK_OBJTECHPROT] PRIMARY KEY NONCLUSTERED ([POT_CODE], [POT_ORG]),
  CONSTRAINT [UQ_OBJTECHPROT] UNIQUE CLUSTERED ([POT_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[OBJTECHPROT]
  ADD CONSTRAINT [FK_OBJTECHPROT_ORG] FOREIGN KEY ([POT_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE])
GO

ALTER TABLE [dbo].[OBJTECHPROT]
  ADD CONSTRAINT [FK_OBJTECHPROT_STATION] FOREIGN KEY ([POT_STNID]) REFERENCES [dbo].[STATION] ([STN_ROWID])
GO