CREATE TABLE [dbo].[TYP2] (
  [TYP2_ROWID] [int] IDENTITY,
  [TYP2_TYP1ID] [int] NOT NULL,
  [TYP2_CODE] [nvarchar](30) NOT NULL,
  [TYP2_DESC] [nvarchar](80) NULL,
  [TYP2_ORDER] [int] NULL,
  CONSTRAINT [PK_TYP2] PRIMARY KEY CLUSTERED ([TYP2_TYP1ID], [TYP2_CODE]),
  CONSTRAINT [UQ_TYP2] UNIQUE ([TYP2_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[TYP2]
  ADD CONSTRAINT [FK_TYP2_TYP1] FOREIGN KEY ([TYP2_TYP1ID]) REFERENCES [dbo].[TYP] ([TYP_ROWID])
GO