CREATE TABLE [dbo].[SAPO_ZWFOT31DON] (
  [OT31DON_ROWID] [int] IDENTITY,
  [OT31DON_LP] [int] NULL,
  [OT31DON_BUKRS] [nvarchar](30) NULL,
  [OT31DON_ANLN1] [nvarchar](30) NULL,
  [OT31DON_ANLN2] [nvarchar](8) NULL,
  [OT31DON_ZMT_ROWID] [int] NULL,
  [OT31DON_OT31ID] [int] NULL,
  CONSTRAINT [PK_SAPO_ZWFOT31DON] PRIMARY KEY CLUSTERED ([OT31DON_ROWID])
)
ON [PRIMARY]
GO