CREATE TABLE [dbo].[PROPERTIES_LIST] (
  [PRL_CODE] [nvarchar](30) NULL,
  [PRL_TEXT] [nvarchar](255) NULL,
  [PRL_UPDATECOUNT] [numeric](38) NULL CONSTRAINT [DF__PROPERTIE__PRL_U__2137ADC7] DEFAULT (0),
  [PRL_CREATED] [datetime] NULL CONSTRAINT [DF__PROPERTIE__PRL_C__222BD200] DEFAULT (getdate()),
  [PRL_UPDATED] [datetime] NULL CONSTRAINT [DF__PROPERTIE__PRL_U__231FF639] DEFAULT (getdate()),
  [PRL_ROWID] [int] IDENTITY,
  [PRL_PROID] [int] NULL,
  CONSTRAINT [PRIK_PRL] PRIMARY KEY NONCLUSTERED ([PRL_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPERTIES_LIST]
  ADD CONSTRAINT [FK_PROPERTIES_LIST_PROPERTIES] FOREIGN KEY ([PRL_PROID]) REFERENCES [dbo].[PROPERTIES] ([PRO_ROWID]) ON DELETE CASCADE ON UPDATE CASCADE
GO