CREATE TABLE [dbo].[ZWFOTDON] (
  [OTD_ROWID] [int] IDENTITY,
  [OTD_OTID] [int] NOT NULL,
  [OTD_STATUS] [nvarchar](30) NULL,
  [OTD_RSTATUS] [int] NULL,
  [OTD_ID] [nvarchar](50) NULL CONSTRAINT [df_OTD_ID] DEFAULT (newid()),
  [OTD_ORG] [nvarchar](30) NULL,
  [OTD_CODE] [nvarchar](30) NULL,
  [OTD_TYPE] [nvarchar](30) NULL,
  [OTD_CREDATE] [datetime] NULL,
  [OTD_CREUSER] [nvarchar](30) NULL,
  [OTD_UPDUSER] [nvarchar](30) NULL,
  [OTD_UPDDATE] [datetime] NULL,
  [OTD_OBJID] [int] NULL,
  [OTD_NOTUSED] [int] NULL DEFAULT (0),
  CONSTRAINT [PK_SAPO_ZWFOTDON] PRIMARY KEY CLUSTERED ([OTD_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZWFOTDON]
  ADD CONSTRAINT [FK_ZWFOTDON_OBJ] FOREIGN KEY ([OTD_OBJID]) REFERENCES [dbo].[OBJ] ([OBJ_ROWID])
GO

ALTER TABLE [dbo].[ZWFOTDON]
  ADD CONSTRAINT [FK_ZWFOTDON_ORG] FOREIGN KEY ([OTD_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE])
GO

ALTER TABLE [dbo].[ZWFOTDON]
  ADD CONSTRAINT [FK_ZWFOTDON_ZWFOT] FOREIGN KEY ([OTD_OTID]) REFERENCES [dbo].[ZWFOT] ([OT_ROWID])
GO