CREATE TABLE [dbo].[DESCRIPTIONS] (
  [ROWID] [int] IDENTITY,
  [DES_ENTITY] [nvarchar](10) NOT NULL,
  [DES_TYPE] [nvarchar](10) NOT NULL,
  [DES_LANGID] [nvarchar](10) NOT NULL,
  [DES_CODE] [nvarchar](100) NOT NULL,
  [DES_TEXT] [nvarchar](80) NULL,
  [DES_CREUSER] [nvarchar](30) NULL CONSTRAINT [DF_DESCRIPTIONS_DES_CREUSER] DEFAULT (N'SA'),
  [DES_CREDATE] [datetime] NULL CONSTRAINT [DF_DESCRIPTIONS_DES_CREDATE] DEFAULT (getdate()),
  [DES_UPDUSER] [nvarchar](30) NULL,
  [DES_UPDDATE] [datetime] NULL,
  CONSTRAINT [PK_DESCRIPTIONS] PRIMARY KEY CLUSTERED ([DES_ENTITY], [DES_TYPE], [DES_LANGID], [DES_CODE]),
  CONSTRAINT [CK_DES_TYPE] CHECK ([DES_TYPE]='STAT' OR [DES_TYPE]='TYP1' OR [DES_TYPE]='TYP2' OR [DES_TYPE]='TYP3' OR [DES_TYPE]='DESC' OR [DES_TYPE]='LOVS')
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[DESCRIPTIONS]
  ADD CONSTRAINT [FK_DESCRIPTIONS_ENT] FOREIGN KEY ([DES_ENTITY]) REFERENCES [dbo].[ENT] ([ENT_CODE])
GO

ALTER TABLE [dbo].[DESCRIPTIONS]
  ADD CONSTRAINT [FK_DESCRIPTIONS_VS_Langs] FOREIGN KEY ([DES_LANGID]) REFERENCES [dbo].[VS_Langs] ([LangID])
GO