CREATE TABLE [dbo].[PRVTYPE] (
  [PTY_ROWID] [int] IDENTITY,
  [PTY_GROUP] [nvarchar](20) NOT NULL,
  [PTY_ENTITY] [nvarchar](10) NOT NULL,
  [PTY_TYPE] [nvarchar](30) NOT NULL,
  CONSTRAINT [PK_PRVTYPE] PRIMARY KEY CLUSTERED ([PTY_GROUP], [PTY_ENTITY], [PTY_TYPE])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRVTYPE]
  ADD CONSTRAINT [FK_PRVTYPE_GROUP] FOREIGN KEY ([PTY_GROUP]) REFERENCES [dbo].[SYGroups] ([GroupID]) ON DELETE CASCADE ON UPDATE CASCADE
GO