CREATE TABLE [dbo].[MAILPROFILES] (
  [ROWID] [int] IDENTITY,
  [MAIP_NAME] [nvarchar](50) NULL,
  [MAIP_COPYRECIPIENTS] [nvarchar](255) NULL,
  [MAIP_BLINDCOPYRECIPIENTS] [nvarchar](255) NULL,
  [MAIP_FROMADDRESS] [nvarchar](255) NULL,
  [MAIP_BODYBEGIN] [nvarchar](255) NULL,
  [MAIP_BODYEND] [nvarchar](255) NULL,
  [MAIP_SUBJECTBEGIN] [nvarchar](255) NULL,
  [MAIP_SUBJECTEND] [nvarchar](255) NULL,
  CONSTRAINT [PK_MAILPROFILES] PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO