CREATE TABLE [dbo].[prv_bez_sts] (
  [PRV_PROID] [int] NOT NULL,
  [PRV_PKID] [int] NULL,
  [PRV_ENT] [nvarchar](10) NULL,
  [PRV_VALUE] [nvarchar](40) NULL,
  [PRV_NVALUE] [numeric](24, 6) NULL,
  [PRV_DVALUE] [datetime] NULL,
  [PRV_UPDATECOUNT] [numeric](38) NULL,
  [PRV_CREATED] [datetime] NULL,
  [PRV_UPDATED] [datetime] NULL,
  [PRV_ROWID] [int] NOT NULL,
  [PRV_NOTUSED] [nvarchar](1) NULL,
  [PRV_ERROR] [nvarchar](255) NULL,
  [OBJ_ROWID] [int] NOT NULL,
  [OBJ_CODE] [nvarchar](30) NOT NULL,
  [OBJ_ORG] [nvarchar](30) NOT NULL,
  [OBJ_DESC] [nvarchar](80) NULL,
  [OBJ_ANOID] [int] NULL,
  [OBJ_INOID] [int] NULL,
  [OBJ_OTID] [int] NULL,
  [OBJ_OTLID] [int] NULL,
  [OBJ_PSPID] [int] NULL,
  [OBJ_STSID] [int] NULL,
  [OBJ_PARENTID] [int] NULL,
  [OBJ_SIGNED] [smallint] NULL,
  [OBJ_SIGNLOC] [nvarchar](80) NULL,
  [OBJ_LEFT] [int] NULL,
  [OBJ_PM_TOSEND] [int] NULL,
  [OBJ_DATE] [datetime] NULL,
  [OBJ_STATUS] [nvarchar](30) NULL,
  [OBJ_TYPE] [nvarchar](30) NULL,
  [OBJ_TYPE2] [nvarchar](30) NULL,
  [OBJ_TYPE3] [nvarchar](30) NULL,
  [OBJ_RSTATUS] [int] NULL,
  [OBJ_CREUSER] [nvarchar](30) NULL,
  [OBJ_CREDATE] [datetime] NULL,
  [OBJ_UPDUSER] [nvarchar](30) NULL,
  [OBJ_UPDDATE] [datetime] NULL,
  [OBJ_NOTUSED] [int] NULL,
  [OBJ_ID] [nvarchar](50) NOT NULL,
  [OBJ_ACCOUNTID] [int] NULL,
  [OBJ_ATTACH] [nvarchar](255) NULL,
  [OBJ_CAPACITY] [nvarchar](30) NULL,
  [OBJ_CATALOGNO] [nvarchar](30) NULL,
  [OBJ_COSTCENTERID] [int] NULL,
  [OBJ_TXT01] [nvarchar](30) NULL,
  [OBJ_TXT02] [nvarchar](30) NULL,
  [OBJ_TXT03] [nvarchar](30) NULL,
  [OBJ_TXT04] [nvarchar](30) NULL,
  [OBJ_TXT05] [nvarchar](30) NULL,
  [OBJ_TXT06] [nvarchar](80) NULL,
  [OBJ_TXT07] [nvarchar](80) NULL,
  [OBJ_TXT08] [nvarchar](255) NULL,
  [OBJ_TXT09] [nvarchar](255) NULL,
  [OBJ_TXT10] [nvarchar](80) NULL,
  [OBJ_TXT11] [nvarchar](80) NULL,
  [OBJ_TXT12] [nvarchar](80) NULL,
  [OBJ_NTX01] [numeric](24, 6) NULL,
  [OBJ_NTX02] [numeric](24, 6) NULL,
  [OBJ_NTX03] [numeric](24, 6) NULL,
  [OBJ_NTX04] [numeric](24, 6) NULL,
  [OBJ_NTX05] [numeric](24, 6) NULL,
  [OBJ_COM01] [nvarchar](max) NULL,
  [OBJ_COM02] [nvarchar](max) NULL,
  [OBJ_DTX01] [datetime] NULL,
  [OBJ_DTX02] [datetime] NULL,
  [OBJ_DTX03] [datetime] NULL,
  [OBJ_DTX04] [datetime] NULL,
  [OBJ_DTX05] [datetime] NULL,
  [OBJ_GROUPID] [int] NULL,
  [OBJ_LOCID] [int] NULL,
  [OBJ_LOCATION] [nvarchar](50) NULL,
  [OBJ_MANUFACID] [int] NULL,
  [OBJ_PARTSLISTID] [int] NULL,
  [OBJ_PERSON] [nvarchar](30) NULL,
  [OBJ_SERIAL] [nvarchar](30) NULL,
  [OBJ_VALUE] [numeric](18, 2) NULL,
  [OBJ_VENDORID] [int] NULL,
  [OBJ_YEAR] [nvarchar](30) NULL,
  [OBJ_MRCID] [int] NULL,
  [OBJ_PREFERED] [int] NULL,
  [OBJ_COMPLEX] [int] NULL,
  [OBJ_NOTE] [nvarchar](max) NULL,
  [OBJ_PM] [nvarchar](30) NULL,
  [OBJ_OT33ID] [int] NULL,
  [OBJ_SIGNEDEXISTS] [int] NULL,
  [OBJ_PM_SERVICE] [nvarchar](30) NULL,
  [OBJ_ROWGUID] [uniqueidentifier] NOT NULL,
  [OBJ_PM_NAME] [nvarchar](255) NULL,
  [OBJ_PRINTDATE] [datetime] NULL,
  [OBJ_PM_REQUEST] [nvarchar](30) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO