CREATE TABLE [dbo].[MOVEMENTCHECK] (
  [MOC_ROWID] [int] IDENTITY,
  [MOC_MOVID] [int] NULL,
  [MOC_OBGID] [int] NULL,
  [MOC_CHECKUSER] [nvarchar](30) NULL,
  [MOC_CREUSER] [nvarchar](30) NULL,
  [MOC_CREDATE] [datetime] NULL CONSTRAINT [DF_MOVEMENTCHECK_MOC_CREDATE] DEFAULT (getdate()),
  [MOC_UPDUSER] [nvarchar](30) NULL,
  [MOC_UPDDATE] [datetime] NULL,
  [MOC_CHECKDATE] [datetime] NULL,
  CONSTRAINT [PK_MOVEMENTCHECK] PRIMARY KEY CLUSTERED ([MOC_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVEMENTCHECK]
  ADD CONSTRAINT [FK_MOVEMENTCHECK_MOVEMENT] FOREIGN KEY ([MOC_MOVID]) REFERENCES [dbo].[MOVEMENT] ([MOV_ROWID])
GO

ALTER TABLE [dbo].[MOVEMENTCHECK]
  ADD CONSTRAINT [FK_MOVEMENTCHECK_OBJGROUP] FOREIGN KEY ([MOC_OBGID]) REFERENCES [dbo].[OBJGROUP] ([OBG_ROWID])
GO