CREATE TABLE [dbo].[SAPIO_ActValuesErrors] (
  [SAE_ROWID] [int] IDENTITY,
  [SAE_SAVROWID] [int] NULL,
  [SAE_MESSAGE] [nvarchar](500) NULL,
  [SAE_DATA] [xml] NULL,
  [SAE_CREDATE] [datetime] NOT NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([SAE_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAPIO_ActValuesErrors]
  ADD CONSTRAINT [FK__SAPIO_Act__SAE_S__4A8B7E70] FOREIGN KEY ([SAE_SAVROWID]) REFERENCES [dbo].[SAPIO_ActValuesHeaders] ([SAV_ROWID])
GO