CREATE TABLE [dbo].[IE2_KONTRAHENCI] (
  [ROWID] [bigint] IDENTITY,
  [i_DateTime] [datetime] NOT NULL,
  [Active] [int] NOT NULL,
  [LIFNR] [nvarchar](30) NOT NULL,
  [LAND1] [nvarchar](30) NULL,
  [NAME1] [nvarchar](512) NULL,
  [MCOD1] [nvarchar](512) NULL,
  [NAME2] [nvarchar](512) NULL,
  [NAME3] [nvarchar](512) NULL,
  [NAME4] [nvarchar](512) NULL,
  [ORT01] [nvarchar](30) NULL,
  [ORT02] [nvarchar](30) NULL,
  [PFACH] [nvarchar](30) NULL,
  [PSTL2] [nvarchar](30) NULL,
  [PSTLZ] [nvarchar](30) NULL,
  [MCOD2] [nvarchar](30) NULL,
  [STRAS] [nvarchar](80) NULL,
  [ADRNR] [nvarchar](30) NULL,
  [MCOD3] [nvarchar](30) NULL,
  [ANRED] [nvarchar](30) NULL,
  [BEGRU] [nvarchar](30) NULL,
  [ERDAT] [datetime] NULL,
  [ERNAM] [nvarchar](30) NULL,
  [KTOKK] [nvarchar](30) NULL,
  [KUNNR] [nvarchar](30) NULL,
  [SPRAS] [nvarchar](30) NULL,
  [STCD1] [nvarchar](30) NULL,
  [STCD2] [nvarchar](30) NULL,
  [DOC_NEW_INSERTED] [smallint] NULL DEFAULT (1),
  [POSKI] [nvarchar](50) NULL,
  CONSTRAINT [PK_IE2_KONTRAHENCI] PRIMARY KEY CLUSTERED ([ROWID])
)
ON [PRIMARY]
GO