CREATE TABLE [dbo].[COSTCLASSIFICATION_KST] (
  [CCA_CCFID] [int] NOT NULL,
  [CCA_NDPER_OD] [int] NULL,
  [CCA_NDPER_DO] [int] NULL,
  [CCA_TXTSEG] [nvarchar](50) NULL
)
ON [PRIMARY]
GO

CREATE CLUSTERED INDEX [E2IDX_CCA01c]
  ON [dbo].[COSTCLASSIFICATION_KST] ([CCA_CCFID])
  ON [PRIMARY]
GO