CREATE TABLE [dbo].[SAPO_ZWFOT32LN] (
  [OT32LN_ROWID] [int] IDENTITY,
  [OT32LN_LP] [int] NULL,
  [OT32LN_BUKRS] [nvarchar](30) NULL,
  [OT32LN_ANLN1] [nvarchar](30) NULL,
  [OT32LN_DT_WYDANIA] [datetime] NULL,
  [OT32LN_MPK_WYDANIA] [nvarchar](30) NULL,
  [OT32LN_GDLGRP] [nvarchar](30) NULL,
  [OT32LN_DT_PRZYJECIA] [datetime] NULL,
  [OT32LN_MPK_PRZYJECIA] [nvarchar](10) NULL,
  [OT32LN_UZYTKOWNIK] [nvarchar](30) NULL,
  [OT32LN_ZMT_ROWID] [int] NULL,
  [OT32LN_PRACOWNIK] [nvarchar](8) NULL,
  [OT32LN_ANLN1_PRZYJECIA] [nvarchar](12) NULL,
  [OT32LN_OT32ID] [int] NULL,
  [OT32LN_ANLN1_POSKI] [nvarchar](12) NULL,
  [OT32LN_ANLN1_PRZYJECIA_POSKI] [nvarchar](12) NULL,
  [OT32LN_MPK_WYDANIA_POSKI] [nvarchar](30) NULL,
  [OT32LN_GDLGRP_POSKI] [nvarchar](30) NULL,
  [OT32LN_MPK_PRZYJECIA_POSKI] [nvarchar](10) NULL,
  [OT32LN_UZYTKOWNIK_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT32LN] PRIMARY KEY CLUSTERED ([OT32LN_ROWID])
)
ON [PRIMARY]
GO