CREATE TABLE [dbo].[ADDCLSPROPERTIES] (
  [ACP_PROID] [int] NOT NULL,
  [ACP_ENT] [nvarchar](10) NOT NULL,
  [ACP_CLSID] [int] NOT NULL,
  [ACP_LINE] [numeric](8) NULL,
  [ACP_UOMID] [int] NULL,
  [ACP_LIST] [nchar](1) NULL,
  [ACP_UPDATECOUNT] [numeric](38) NULL DEFAULT (0),
  [ACP_CREATED] [datetime] NULL DEFAULT (getdate()),
  [ACP_UPDATED] [datetime] NULL DEFAULT (getdate()),
  [ACP_ROWID] [int] IDENTITY,
  [ACP_REQUIRED] [nvarchar](3) NULL,
  CONSTRAINT [PRIK_ACP] PRIMARY KEY NONCLUSTERED ([ACP_PROID], [ACP_CLSID]),
  CONSTRAINT [UNQSQL_ACP] UNIQUE ([ACP_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADDCLSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [CHK1_ACP] CHECK ([ACP_list]=N'T' OR [ACP_list]=N'C' OR [ACP_list]=N'E' OR [ACP_list]=N'P' OR [ACP_list]=N'-')
GO

ALTER TABLE [dbo].[ADDCLSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [CHK3_ACP] CHECK ([ACP_REQUIRED]=N'TAK' OR [ACP_REQUIRED]=N'NIE')
GO

ALTER TABLE [dbo].[ADDCLSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK1_ACP] FOREIGN KEY ([ACP_CLSID]) REFERENCES [dbo].[CLASS] ([CLS_ROWID])
GO

ALTER TABLE [dbo].[ADDCLSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK2_ACP] FOREIGN KEY ([ACP_PROID]) REFERENCES [dbo].[PROPERTIES] ([PRO_ROWID])
GO

ALTER TABLE [dbo].[ADDCLSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK3_ACP] FOREIGN KEY ([ACP_UOMID]) REFERENCES [dbo].[UOM] ([UOM_ROWID])
GO