CREATE TABLE [dbo].[SAPO_ZWFOT33DON] (
  [OT33DON_ROWID] [int] IDENTITY,
  [OT33DON_ANLN2] [nvarchar](8) NULL,
  [OT33DON_TXT50] [nvarchar](50) NULL,
  [OT33DON_WARST] [decimal](13, 2) NULL,
  [OT33DON_NDJARPER] [int] NULL,
  [OT33DON_MTOPER] [nvarchar](1) NULL,
  [OT33DON_ANLN1_DO] [nvarchar](12) NULL,
  [OT33DON_ANLN2_DO] [nvarchar](4) NULL,
  [OT33DON_ANLKL_DO] [nvarchar](8) NULL,
  [OT33DON_KOSTL_DO] [nvarchar](10) NULL,
  [OT33DON_UZYTK_DO] [nvarchar](8) NULL,
  [OT33DON_PRAC_DO] [int] NULL,
  [OT33DON_PRCNT_DO] [int] NULL,
  [OT33DON_WARST_DO] [decimal](13, 2) NULL,
  [OT33DON_TXT50_DO] [nvarchar](50) NULL,
  [OT33DON_NDPER_DO] [int] NULL,
  [OT33DON_CHAR_DO] [nvarchar](50) NULL,
  [OT33DON_BELNR] [nvarchar](10) NULL,
  [OT33DON_ZMT_ROWID] [int] NULL,
  [OT33DON_OT33ID] [int] NULL,
  [OT33DON_ANLN1_DO_POSKI] [nvarchar](30) NULL,
  [OT33DON_ANLKL_DO_POSKI] [nvarchar](30) NULL,
  [OT33DON_KOSTL_DO_POSKI] [nvarchar](30) NULL,
  [OT33DON_UZYTK_DO_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT33DON] PRIMARY KEY CLUSTERED ([OT33DON_ROWID]),
  CONSTRAINT [UQ_OT33ID_ANLN2] UNIQUE ([OT33DON_OT33ID], [OT33DON_ANLN2])
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IX_OT33ID_ANLN2]
  ON [dbo].[SAPO_ZWFOT33DON] ([OT33DON_ANLN2], [OT33DON_OT33ID])
  ON [PRIMARY]
GO