CREATE TABLE [dbo].[ST_ASSORT] (
  [ASS_CODE] [nvarchar](30) NOT NULL,
  [ASS_ORG] [nvarchar](30) NOT NULL,
  [ASS_DESC] [varchar](80) NULL,
  [ASS_TYPE] [nvarchar](30) NULL,
  [ASS_TYPE_DESC] [nvarchar](80) NULL,
  [ASS_TYPE2] [nvarchar](30) NULL,
  [ASS_TYPE2_DESC] [nvarchar](80) NULL,
  [ASS_TYPE3] [nvarchar](30) NULL,
  [ASS_TYPE3_DESC] [nvarchar](80) NULL,
  [ASS_CREUSER] [nvarchar](30) NULL,
  [ASS_CREUSER_DESC] [nvarchar](1000) NULL,
  [ASS_CREDATE] [datetime] NULL,
  [ASS_UPDUSER] [nvarchar](30) NULL,
  [ASS_UPDUSER_DESC] [nvarchar](1000) NULL,
  [ASS_UPDDATE] [datetime] NULL,
  [ASS_NOTUSED] [int] NULL,
  [ASS_ID] [nvarchar](50) NULL,
  [TXT01] [nvarchar](30) NULL,
  [TXT02] [nvarchar](30) NULL,
  [TXT03] [nvarchar](30) NULL,
  [TXT04] [nvarchar](30) NULL,
  [TXT05] [nvarchar](30) NULL,
  [TXT06] [nvarchar](80) NULL,
  [TXT07] [nvarchar](80) NULL,
  [TXT08] [nvarchar](255) NULL,
  [TXT09] [nvarchar](255) NULL,
  [NTX01] [numeric](24, 6) NULL,
  [NTX02] [numeric](24, 6) NULL,
  [NTX03] [numeric](24, 6) NULL,
  [NTX04] [numeric](24, 6) NULL,
  [NTX05] [numeric](24, 6) NULL,
  [COM01] [ntext] NULL,
  [COM02] [ntext] NULL,
  [DTX01] [datetime] NULL,
  [DTX02] [datetime] NULL,
  [DTX03] [datetime] NULL,
  [DTX04] [datetime] NULL,
  [DTX05] [datetime] NULL,
  [ASS_UOMID] [int] NULL,
  [ASS_UOM] [nvarchar](30) NULL,
  [ASS_DELIVERYTIME] [numeric](30, 2) NULL,
  [ASS_GRPID] [int] NULL,
  [ASS_GRP_DESC] [varchar](80) NULL,
  [ASS_GRP] [varchar](30) NULL,
  [ASS_PRICE] [numeric](24, 2) NULL,
  [ASS_PRICEUNIT] [numeric](24, 2) NULL,
  [ASS_MARKUP] [numeric](24, 2) NULL,
  [ASS_PRICEQTY] [numeric](24, 2) NULL,
  [ASS_PURCHBLOCKED] [int] NULL,
  [ASS_INVENTBLOCKED] [int] NULL,
  [ASS_VENID] [int] NULL,
  [ASS_VEN] [nvarchar](50) NULL,
  [ASS_ABCLOG] [nvarchar](30) NULL,
  [ASS_ABCVEND] [nvarchar](30) NULL,
  [ASS_USEALTITEMID] [int] NULL,
  [ASS_ALTITEMID] [int] NULL,
  [ASS_ALTITEM] [nvarchar](30) NULL,
  [ASS_AXAID] [bigint] NULL,
  [ASS_QTY] [numeric](30, 6) NULL,
  [ASS_ORDQTY] [numeric](38, 6) NULL,
  [ISMIN_MAX] [int] NULL,
  [ASS_ISTOOL] [smallint] NULL,
  [rowguid] [uniqueidentifier] NOT NULL CONSTRAINT [DF__ST_ASSORT__rowgu__29221CFB] DEFAULT (newid()),
  CONSTRAINT [PK_ST_ASSORT] PRIMARY KEY NONCLUSTERED ([rowguid])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO