CREATE TABLE [dbo].[OBJPARTSLIST] (
  [OPL_ROWID] [int] IDENTITY,
  [OPL_CODE] [nvarchar](30) NOT NULL,
  [OPL_ORG] [nvarchar](30) NOT NULL,
  [OPL_DESC] [nvarchar](80) NULL,
  [OPL_NOTE] [ntext] NULL,
  [OPL_DATE] [datetime] NULL,
  [OPL_STATUS] [nvarchar](30) NULL,
  [OPL_TYPE] [nvarchar](30) NULL,
  [OPL_TYPE2] [nvarchar](30) NULL,
  [OPL_TYPE3] [nvarchar](30) NULL,
  [OPL_RSTATUS] [int] NULL,
  [OPL_CREUSER] [nvarchar](30) NULL CONSTRAINT [DF_OBJPARTSLIST_OPL_CREUSER] DEFAULT (N'SA'),
  [OPL_CREDATE] [datetime] NULL CONSTRAINT [DF_OBJPARTSLIST__CREDATE] DEFAULT (getdate()),
  [OPL_UPDUSER] [nvarchar](30) NULL,
  [OPL_UPDDATE] [datetime] NULL,
  [OPL_NOTUSED] [int] NULL,
  [OPL_ID] [nvarchar](50) NULL CONSTRAINT [DF_OBJPARTSLIST__ID] DEFAULT (CONVERT([nvarchar](50),newid(),(0))),
  [OPL_TXT01] [nvarchar](30) NULL,
  [OPL_TXT02] [nvarchar](30) NULL,
  [OPL_TXT03] [nvarchar](30) NULL,
  [OPL_TXT04] [nvarchar](30) NULL,
  [OPL_TXT05] [nvarchar](30) NULL,
  [OPL_TXT06] [nvarchar](80) NULL,
  [OPL_TXT07] [nvarchar](80) NULL,
  [OPL_TXT08] [nvarchar](255) NULL,
  [OPL_TXT09] [nvarchar](255) NULL,
  [OPL_NTX01] [numeric](24, 6) NULL,
  [OPL_NTX02] [numeric](24, 6) NULL,
  [OPL_NTX03] [numeric](24, 6) NULL,
  [OPL_NTX04] [numeric](24, 6) NULL,
  [OPL_NTX05] [numeric](24, 6) NULL,
  [OPL_COM01] [ntext] NULL,
  [OPL_COM02] [ntext] NULL,
  [OPL_DTX01] [datetime] NULL,
  [OPL_DTX02] [datetime] NULL,
  [OPL_DTX03] [datetime] NULL,
  [OPL_DTX04] [datetime] NULL,
  [OPL_DTX05] [datetime] NULL,
  CONSTRAINT [PK_OBJPARTSLIST] PRIMARY KEY NONCLUSTERED ([OPL_CODE], [OPL_ORG]),
  CONSTRAINT [UQ_OBJPARTSLIST] UNIQUE ([OPL_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO