CREATE TABLE [dbo].[VS_KPIUSERSGROUP] (
  [ROWID] [int] IDENTITY,
  [KPG_KPIID] [int] NOT NULL,
  [KPG_GROUPID] [nvarchar](20) NOT NULL,
  [LastUpdate] [datetime] NULL,
  [UpdateUser] [nvarchar](100) NULL,
  [UpdateInfo] [nvarchar](255) NULL,
  CONSTRAINT [PK_VS_KPIUSERSGROUP] PRIMARY KEY NONCLUSTERED ([KPG_KPIID], [KPG_GROUPID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[VS_KPIUSERSGROUP]
  ADD CONSTRAINT [FK_VS_KPIUSERSGROUP_VS_KPI] FOREIGN KEY ([KPG_KPIID]) REFERENCES [dbo].[VS_KPI] ([ROWID])
GO