CREATE TABLE [dbo].[AST_ANLKLX] (
  [ANLKL_OD] [nvarchar](30) NOT NULL,
  [ANLKL_DO] [nvarchar](30) NOT NULL,
  [WYBOR] [tinyint] NOT NULL CONSTRAINT [DF_AST_ANLKLX_WYBOR] DEFAULT (0),
  CONSTRAINT [PK_AST_ANLKLX] PRIMARY KEY CLUSTERED ([ANLKL_OD], [ANLKL_DO])
)
ON [PRIMARY]
GO