CREATE TABLE [dbo].[OBJTECHPROTLN_POL_COM03_HISTORY] (
  [OCH_SQLIDENTITY] [int] IDENTITY,
  [OCH_POLROWID] [int] NULL,
  [OCH_COM] [ntext] NULL,
  [OCH_USERID] [nvarchar](30) NULL,
  [OCH_DATE] [datetime] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO