CREATE TABLE [dbo].[PRVMAG] (
  [OPR_GROUP] [nvarchar](20) NOT NULL,
  [OPR_MAGID] [int] NOT NULL,
  [OPR_RW] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW] DEFAULT (0),
  [OPR_ZW] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW1] DEFAULT (0),
  [OPR_PR] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW2] DEFAULT (0),
  [OPR_RV] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW3] DEFAULT (0),
  [OPR_MM_FROM] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW5] DEFAULT (0),
  [OPR_MM_TO] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW6] DEFAULT (0),
  [OPR_QR] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW7] DEFAULT (0),
  [OPR_IT] [numeric](24) NULL CONSTRAINT [DF_st_magprv_OPR_RW8] DEFAULT (0),
  [OPR_DEFAULT] [int] NULL,
  CONSTRAINT [PK_PRVMAG] PRIMARY KEY CLUSTERED ([OPR_GROUP], [OPR_MAGID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRVMAG]
  ADD CONSTRAINT [FK_PRVMAG_PRVMAG] FOREIGN KEY ([OPR_GROUP]) REFERENCES [dbo].[SYGroups] ([GroupID])
GO