CREATE TABLE [dbo].[INVTSK_STATIONS] (
  [INS_ROWID] [int] IDENTITY,
  [INS_ITSID] [int] NOT NULL,
  [INS_STNID] [int] NOT NULL,
  CONSTRAINT [PK_INVTSK_STATIONS] PRIMARY KEY CLUSTERED ([INS_ITSID], [INS_STNID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[INVTSK_STATIONS]
  ADD CONSTRAINT [FK_INS_INVTSK] FOREIGN KEY ([INS_ITSID]) REFERENCES [dbo].[INVTSK] ([ITS_ROWID])
GO

ALTER TABLE [dbo].[INVTSK_STATIONS]
  ADD CONSTRAINT [FK_INS_STATIONS] FOREIGN KEY ([INS_STNID]) REFERENCES [dbo].[STATION] ([STN_ROWID])
GO