CREATE TABLE [dbo].[ST_MAGPRV] (
  [GroupID] [nvarchar](10) NOT NULL,
  [MagID] [int] NOT NULL,
  [PR_ADDNEW] [smallint] NULL,
  [PR_DELETE] [smallint] NULL,
  [PR_SAVE] [smallint] NULL,
  [PR_ACCEPT] [smallint] NULL,
  [QR_ADDNEW] [smallint] NULL,
  [QR_DELETE] [smallint] NULL,
  [QR_SAVE] [smallint] NULL,
  [QR_ACCEPT] [smallint] NULL,
  [IC_ADDNEW] [smallint] NULL,
  [IC_DELETE] [smallint] NULL,
  [IC_SAVE] [smallint] NULL,
  [IC_ACCEPT] [smallint] NULL,
  [IR_ADDNEW] [smallint] NULL,
  [IR_DELETE] [smallint] NULL,
  [IR_SAVE] [smallint] NULL,
  [IR_ACCEPT] [smallint] NULL,
  [KR_ADDNEW] [smallint] NULL,
  [KR_DELETE] [smallint] NULL,
  [KR_SAVE] [smallint] NULL,
  [KR_ACCEPT] [smallint] NULL,
  [MV_ADDNEW] [smallint] NULL,
  [MV_DELETE] [smallint] NULL,
  [MV_SAVE] [smallint] NULL,
  [MV_ACCEPT] [smallint] NULL,
  [IT_ADDNEW] [smallint] NULL,
  [IT_DELETE] [smallint] NULL,
  [IT_SAVE] [smallint] NULL,
  [IT_ACCEPT] [smallint] NULL,
  [QS_ADDNEW] [smallint] NULL,
  [QS_DELETE] [smallint] NULL,
  [QS_SAVE] [smallint] NULL,
  [QS_ACCEPT] [smallint] NULL,
  [RV_ADDNEW] [smallint] NULL,
  [RV_DELETE] [smallint] NULL,
  [RV_SAVE] [smallint] NULL,
  [RV_ACCEPT] [smallint] NULL,
  CONSTRAINT [PK_st_magprv] PRIMARY KEY CLUSTERED ([GroupID], [MagID])
)
ON [PRIMARY]
GO