CREATE TABLE [dbo].[PRVORG] (
  [POR_GROUP] [nvarchar](20) NOT NULL,
  [POR_ORG] [nvarchar](30) NOT NULL,
  [POR_DEFAULT] [int] NULL CONSTRAINT [DF_PRVORG_POR_DEFAULT] DEFAULT (0),
  CONSTRAINT [PK_PRVORG] PRIMARY KEY CLUSTERED ([POR_GROUP], [POR_ORG])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRVORG]
  ADD CONSTRAINT [FK_PRVORG_GROUP] FOREIGN KEY ([POR_GROUP]) REFERENCES [dbo].[SYGroups] ([GroupID]) ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[PRVORG]
  ADD CONSTRAINT [FK_PRVORG_ORG] FOREIGN KEY ([POR_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE]) ON UPDATE CASCADE
GO