CREATE TABLE [dbo].[SAPIO_ActValuesLines] (
  [SAL_ROWID] [int] IDENTITY,
  [SAL_SAVROWID] [int] NOT NULL,
  [SAL_ASTROWID] [int] NOT NULL,
  [SAL_INITIALVALUE] [numeric](24, 6) NULL,
  [SAL_NETVALUE] [numeric](24, 6) NULL,
  [SAL_AMORTIZATIONPERIOD] [nvarchar](30) NULL,
  CONSTRAINT [PK__SAPIO_Ac__9B114E260D880E44] PRIMARY KEY CLUSTERED ([SAL_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAPIO_ActValuesLines]
  ADD CONSTRAINT [FK__SAPIO_Act__SAL_A__45C6C953] FOREIGN KEY ([SAL_ASTROWID]) REFERENCES [dbo].[ASSET] ([AST_ROWID])
GO

ALTER TABLE [dbo].[SAPIO_ActValuesLines]
  ADD CONSTRAINT [FK__SAPIO_Act__SAL_S__46BAED8C] FOREIGN KEY ([SAL_SAVROWID]) REFERENCES [dbo].[SAPIO_ActValuesHeaders] ([SAV_ROWID])
GO