CREATE TABLE [dbo].[SAPO_ZWFOT31LN] (
  [OT31LN_ROWID] [int] IDENTITY,
  [OT31LN_LP] [int] NULL,
  [OT31LN_BUKRS] [nvarchar](30) NULL,
  [OT31LN_ANLN1] [nvarchar](30) NULL,
  [OT31LN_UZASADNIENIE] [nvarchar](50) NULL,
  [OT31LN_DT_WYDANIA] [datetime] NULL,
  [OT31LN_MPK_WYDANIA] [nvarchar](30) NULL,
  [OT31LN_GDLGRP] [nvarchar](30) NULL,
  [OT31LN_DT_PRZYJECIA] [datetime] NULL,
  [OT31LN_MPK_PRZYJECIA] [nvarchar](10) NULL,
  [OT31LN_UZYTKOWNIK] [nvarchar](30) NULL,
  [OT31LN_ZMT_ROWID] [int] NULL,
  [OT31LN_PRACOWNIK] [nvarchar](8) NULL,
  [OT31LN_OT31ID] [int] NULL,
  [OT31LN_ANLN1_POSKI] [nvarchar](30) NULL,
  [OT31LN_MPK_WYDANIA_POSKI] [nvarchar](30) NULL,
  [OT31LN_GDLGRP_POSKI] [nvarchar](30) NULL,
  [OT31LN_MPK_PRZYJECIA_POSKI] [nvarchar](30) NULL,
  [OT31LN_UZYTKOWNIK_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT31LN] PRIMARY KEY CLUSTERED ([OT31LN_ROWID])
)
ON [PRIMARY]
GO