CREATE TABLE [dbo].[OBJASSET] (
  [OBA_ROWID] [int] IDENTITY,
  [OBA_OBJID] [int] NOT NULL,
  [OBA_ASTID] [int] NOT NULL,
  [OBA_CREDATE] [datetime] NULL CONSTRAINT [DF_OBJASSET_CREDATE] DEFAULT (getdate()),
  [OBA_CREUSER] [nvarchar](30) NULL,
  [OBA_UPDDATE] [datetime] NULL,
  [OBA_UPDUSER] [nvarchar](30) NULL,
  CONSTRAINT [PK_OBJASSET_1] PRIMARY KEY CLUSTERED ([OBA_OBJID], [OBA_ASTID]),
  CONSTRAINT [UQ_OBJASSET] UNIQUE ([OBA_ROWID])
)
ON [PRIMARY]
GO

CREATE INDEX [E2IDX_OBA01]
  ON [dbo].[OBJASSET] ([OBA_OBJID])
  ON [PRIMARY]
GO

CREATE INDEX [E2IDX_OBA02]
  ON [dbo].[OBJASSET] ([OBA_ASTID])
  ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[OBJASSET_GROUPID_ASSET_UPDATE]
   ON  [dbo].[OBJASSET]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

declare @v_AST_ROWID int
declare @v_OBA_OBJID int
declare @v_OBJ_GROUPID int

	select @v_AST_ROWID = OBA_ASTID, @v_OBA_OBJID = OBA_OBJID from inserted

	select @v_OBJ_GROUPID = obj_groupid from OBJ where OBJ_ROWID = @v_OBA_OBJID

	if (@v_OBA_OBJID is not null and @v_OBJ_GROUPID is not null)
		update dbo.ASSET
		set AST_OBJGROUPID = @v_OBJ_GROUPID
		where AST_ROWID = @v_AST_ROWID

END
GO

ALTER TABLE [dbo].[OBJASSET]
  ADD CONSTRAINT [FK_OBJASSET_AST] FOREIGN KEY ([OBA_ASTID]) REFERENCES [dbo].[ASSET] ([AST_ROWID]) ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[OBJASSET]
  ADD CONSTRAINT [FK_OBJASSET_OBJ] FOREIGN KEY ([OBA_OBJID]) REFERENCES [dbo].[OBJ] ([OBJ_ROWID]) ON UPDATE CASCADE
GO