CREATE TABLE [dbo].[_RM_PSPIMP] (
  [KOD_ZAD] [nvarchar](50) NOT NULL,
  [REC_STATUS] [nvarchar](50) NULL CONSTRAINT [DF__RM_PSPIMP_REC_STATUS] DEFAULT (N'CREATED'),
  [REC_DESC] [nvarchar](50) NULL,
  [REC_COUNT] [int] NULL,
  CONSTRAINT [PK__RM_PSPIMP] PRIMARY KEY CLUSTERED ([KOD_ZAD])
)
ON [PRIMARY]
GO