CREATE TABLE [dbo].[SAPO_ZWFOT41LN] (
  [OT41LN_ROWID] [int] IDENTITY,
  [OT41LN_BUKRS] [nvarchar](30) NULL,
  [OT41LN_ANLN1] [nvarchar](41) NULL,
  [OT41LN_KOSTL] [nvarchar](10) NULL,
  [OT41LN_GDLGRP] [nvarchar](8) NULL,
  [OT41LN_UZASA] [nvarchar](50) NULL,
  [OT41LN_MENGE] [decimal](26, 3) NULL,
  [OT41LN_ZMT_ROWID] [int] NULL,
  [OT41LN_OT41ID] [int] NULL,
  [OT41LN_ANLN1_POSKI] [nvarchar](30) NULL,
  [OT41LN_KOSTL_POSKI] [nvarchar](30) NULL,
  [OT41LN_GDLGRP_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT41LN] PRIMARY KEY CLUSTERED ([OT41LN_ROWID])
)
ON [PRIMARY]
GO