CREATE TABLE [dbo].[SAPO_ZWFOT11CHAR] (
  [OT11CHAR_ROWID] [int] IDENTITY,
  [OT11CHAR_TDFORMAT] [nvarchar](2) NULL,
  [OT11CHAR_TDLINE] [nvarchar](132) NULL,
  [OT11CHAR_OT11ID] [int] NULL,
  [OT11CHAR_CREDATE] [datetime] NULL DEFAULT (getdate()),
  [OT11CHAR_CREUSER] [nvarchar](30) NULL DEFAULT ('AUTO')
)
ON [PRIMARY]
GO