CREATE TABLE [dbo].[ZWFOTOBJ] (
  [OTO_ROWID] [int] IDENTITY,
  [OTO_OTID] [int] NOT NULL,
  [OTO_OTLID] [int] NULL,
  [OTO_OBJID] [int] NOT NULL,
  [OTO_ASTCODE] [nvarchar](30) NULL,
  [OTO_ASTSUBCODE] [nvarchar](10) NULL,
  [OTO_CREUSER] [nvarchar](30) NULL,
  [OTO_CREDATE] [datetime] NULL,
  CONSTRAINT [PK_ZWFOTOBJ] PRIMARY KEY CLUSTERED ([OTO_OTID], [OTO_OBJID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZWFOTOBJ]
  ADD CONSTRAINT [FK_ZWFOTOBJ_OBJ] FOREIGN KEY ([OTO_OBJID]) REFERENCES [dbo].[OBJ] ([OBJ_ROWID])
GO

ALTER TABLE [dbo].[ZWFOTOBJ]
  ADD CONSTRAINT [FK_ZWFOTOBJ_ZWFOT] FOREIGN KEY ([OTO_OTID]) REFERENCES [dbo].[ZWFOT] ([OT_ROWID])
GO

ALTER TABLE [dbo].[ZWFOTOBJ]
  ADD CONSTRAINT [FK_ZWFOTOBJ_ZWFOTLN] FOREIGN KEY ([OTO_OTLID]) REFERENCES [dbo].[ZWFOTLN] ([OTL_ROWID])
GO