CREATE TABLE [dbo].[SYExMaps] (
  [MapID] [nvarchar](50) NOT NULL,
  [TableName] [nvarchar](50) NULL,
  [FieldName] [nvarchar](50) NULL,
  [IsFixedColumn] [bit] NULL,
  [IsFixedRow] [bit] NULL,
  [IsDisable] [bit] NULL,
  [BLeft] [bit] NULL,
  [BTop] [bit] NULL,
  [BBottom] [bit] NULL,
  [BRight] [bit] NULL,
  [ForeColor] [nvarchar](10) NULL,
  [ForeColorAlt] [nvarchar](10) NULL,
  [Font] [nvarchar](50) NULL,
  [FontSize] [int] NULL,
  [BGColor] [nvarchar](10) NULL,
  [BGColorAlt] [nvarchar](10) NULL,
  [Type] [nvarchar](20) NULL,
  [HorizontalAlignment] [nvarchar](20) NULL,
  [VerticalAlignment] [nvarchar](20) NULL,
  [BLeftWeight] [nvarchar](15) NULL,
  [BTopWeight] [nvarchar](15) NULL,
  [BBottomWeight] [nvarchar](15) NULL,
  [BRightWeight] [nvarchar](15) NULL,
  [BLeftLineStyle] [nvarchar](15) NULL,
  [BTopLineStyle] [nvarchar](15) NULL,
  [BBottomLineStyle] [nvarchar](15) NULL,
  [BRightLineStyle] [nvarchar](15) NULL,
  [ColumnWidth] [numeric](18, 2) NULL,
  [Orientation] [int] NULL,
  [Bold] [bit] NULL,
  [Italic] [bit] NULL,
  [Underline] [bit] NULL,
  [ExColumn] [nvarchar](10) NULL,
  [ExRow] [nvarchar](10) NULL,
  [RowHeight] [numeric](18, 2) NULL,
  [WrapText] [bit] NULL,
  [Autofit] [bit] NULL,
  [Option] [nvarchar](4000) NULL,
  [Formula] [nvarchar](4000) NULL,
  [NumberFormat] [nvarchar](100) NULL,
  [BRightColor] [nvarchar](10) NULL,
  [BLeftColor] [nvarchar](10) NULL,
  [BTopColor] [nvarchar](10) NULL,
  [BBottomColor] [nvarchar](10) NULL,
  [ReportID] [nvarchar](50) NULL,
  [LastUpdate] [datetime] NULL,
  [UpdateInfo] [nvarchar](255) NULL,
  [UpdateUser] [nvarchar](100) NULL,
  CONSTRAINT [PK_SYExMaps] PRIMARY KEY NONCLUSTERED ([MapID])
)
ON [PRIMARY]
GO