CREATE TABLE [dbo].[PMKLASACECHA] (
  [PKC_ROWID] [int] IDENTITY,
  [PKC_KLASA] [nvarchar](30) NOT NULL,
  [PKC_KLASA_OPIS] [nvarchar](80) NULL,
  [PKC_CECHA] [nvarchar](30) NOT NULL,
  [PKC_CECHA_OPIS] [nvarchar](80) NULL,
  [PKC_TYP] [nvarchar](1) NULL,
  CONSTRAINT [PK_PMKLASACECHA] PRIMARY KEY CLUSTERED ([PKC_KLASA], [PKC_CECHA])
)
ON [PRIMARY]
GO