CREATE TABLE [dbo].[COSTCENTER] (
  [CCT_ROWID] [int] IDENTITY,
  [CCT_CODE] [nvarchar](30) NOT NULL,
  [CCT_ORG] [nvarchar](30) NOT NULL,
  [CCT_DESC] [nvarchar](80) NULL,
  [CCT_NOTUSED] [int] NULL,
  [CCT_CREDATE] [datetime] NULL,
  [CCT_CREUSER] [nvarchar](30) NULL,
  [CCT_UPDDATE] [datetime] NULL,
  [CCT_UPDUSER] [nvarchar](30) NULL,
  CONSTRAINT [PK_COSTCENTER] PRIMARY KEY CLUSTERED ([CCT_CODE], [CCT_ORG]),
  CONSTRAINT [UQ_COSTCENTER] UNIQUE ([CCT_ROWID])
)
ON [PRIMARY]
GO