CREATE TABLE [dbo].[STENCILLN] (
  [STL_PARENTID] [int] NOT NULL,
  [STL_CHILDID] [int] NOT NULL,
  [STL_ORG] [nvarchar](30) NOT NULL,
  [STL_ROWID] [int] IDENTITY,
  [STL_REQUIRED] [nvarchar](3) NULL,
  [STL_ONE] [nvarchar](3) NULL,
  [STL_DEFAULT_NUMBER] [int] NULL,
  CONSTRAINT [PK_STENCILLN] PRIMARY KEY CLUSTERED ([STL_PARENTID], [STL_CHILDID], [STL_ORG]),
  CONSTRAINT [IX_STENCILLN_1] UNIQUE ([STL_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[STENCILLN] WITH NOCHECK
  ADD CONSTRAINT [CHK3_STL] CHECK ([STL_REQUIRED]=N'TAK' OR [STL_REQUIRED]=N'NIE')
GO

ALTER TABLE [dbo].[STENCILLN] WITH NOCHECK
  ADD CONSTRAINT [CHK4_STL] CHECK ([STL_ONE]=N'TAK' OR [STL_ONE]=N'NIE')
GO

ALTER TABLE [dbo].[STENCILLN]
  ADD CONSTRAINT [FK_STENCILLN_ORG] FOREIGN KEY ([STL_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE]) ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[STENCILLN] WITH NOCHECK
  ADD CONSTRAINT [FK_STENCILLN_STS] FOREIGN KEY ([STL_PARENTID]) REFERENCES [dbo].[STENCIL] ([STS_ROWID])
GO

ALTER TABLE [dbo].[STENCILLN] WITH NOCHECK
  ADD CONSTRAINT [FK_STENCILLN_STS1] FOREIGN KEY ([STL_CHILDID]) REFERENCES [dbo].[STENCIL] ([STS_ROWID])
GO