CREATE TABLE [dbo].[SAPO_ZWFOT42LN] (
  [OT42LN_ROWID] [int] IDENTITY,
  [OT42LN_BUKRS] [nvarchar](30) NULL,
  [OT42LN_ANLN1] [nvarchar](42) NULL,
  [OT42LN_ANLN2] [nvarchar](4) NULL,
  [OT42LN_KOSTL] [nvarchar](10) NULL,
  [OT42LN_GDLGRP] [nvarchar](8) NULL,
  [OT42LN_ODZYSK] [nvarchar](3) NULL,
  [OT42LN_LIKWCZESC] [nvarchar](1) NULL,
  [OT42LN_PROC] [decimal](10, 2) NULL,
  [OT42LN_ZMT_ROWID] [int] NULL,
  [OT42LN_OT42ID] [int] NULL,
  [OT42LN_ANLN1_POSKI] [nvarchar](30) NULL,
  [OT42LN_KOSTL_POSKI] [nvarchar](30) NULL,
  [OT42LN_GDLGRP_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT42LN] PRIMARY KEY CLUSTERED ([OT42LN_ROWID])
)
ON [PRIMARY]
GO