CREATE TABLE [dbo].[MOVEMENTLN] (
  [MOL_ROWID] [int] IDENTITY,
  [MOL_MOVID] [int] NOT NULL,
  [MOL_OBJID] [int] NULL,
  [MOL_CODE] [nvarchar](30) NULL,
  [MOL_ROWGUID] [uniqueidentifier] NULL CONSTRAINT [DF__MOVEMENTLN__MOL_R__483D01AD] DEFAULT (newid()),
  [MOL_ORG] [nvarchar](30) NULL,
  [MOL_PRICE] [numeric](30, 6) NULL,
  [MOL_DESC] [nvarchar](80) NULL,
  [MOL_NOTE] [ntext] NULL,
  [MOL_DATE] [datetime] NULL,
  [MOL_STATUS] [nvarchar](30) NULL,
  [MOL_TYPE] [nvarchar](30) NULL,
  [MOL_TYPE2] [nvarchar](30) NULL,
  [MOL_TYPE3] [nvarchar](30) NULL,
  [MOL_RSTATUS] [int] NULL,
  [MOL_CREUSER] [nvarchar](30) NULL,
  [MOL_CREDATE] [datetime] NULL,
  [MOL_UPDUSER] [nvarchar](30) NULL,
  [MOL_UPDDATE] [datetime] NULL,
  [MOL_NOTUSED] [int] NULL,
  [MOL_ID] [nvarchar](50) NULL CONSTRAINT [DF_MOVEMENTLN__ID] DEFAULT (CONVERT([nvarchar](50),newid(),(0))),
  [MOL_TXT01] [nvarchar](30) NULL,
  [MOL_TXT02] [nvarchar](30) NULL,
  [MOL_TXT03] [nvarchar](30) NULL,
  [MOL_TXT04] [nvarchar](30) NULL,
  [MOL_TXT05] [nvarchar](30) NULL,
  [MOL_TXT06] [nvarchar](80) NULL,
  [MOL_TXT07] [nvarchar](80) NULL,
  [MOL_TXT08] [nvarchar](255) NULL,
  [MOL_TXT09] [nvarchar](255) NULL,
  [MOL_NTX01] [numeric](24, 6) NULL,
  [MOL_NTX02] [numeric](24, 6) NULL,
  [MOL_NTX03] [numeric](24, 6) NULL,
  [MOL_NTX04] [numeric](24, 6) NULL,
  [MOL_NTX05] [numeric](24, 6) NULL,
  [MOL_COM01] [ntext] NULL,
  [MOL_COM02] [ntext] NULL,
  [MOL_DTX01] [datetime] NULL,
  [MOL_DTX02] [datetime] NULL,
  [MOL_DTX03] [datetime] NULL,
  [MOL_DTX04] [datetime] NULL,
  [MOL_DTX05] [datetime] NULL,
  [MOL_TO_STNID] [int] NULL,
  [MOL_OT31ID] [int] NULL,
  [MOL_OT32ID] [int] NULL,
  [MOL_OT33ID] [int] NULL,
  CONSTRAINT [PK_MOVEMENTLN] PRIMARY KEY CLUSTERED ([MOL_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_MOVEMENT] FOREIGN KEY ([MOL_MOVID]) REFERENCES [dbo].[MOVEMENT] ([MOV_ROWID])
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_OBJ] FOREIGN KEY ([MOL_OBJID]) REFERENCES [dbo].[OBJ] ([OBJ_ROWID])
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_ORG] FOREIGN KEY ([MOL_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE])
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_SAPO_ZWFOT31] FOREIGN KEY ([MOL_OT31ID]) REFERENCES [dbo].[SAPO_ZWFOT31] ([OT31_ROWID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_SAPO_ZWFOT32] FOREIGN KEY ([MOL_OT32ID]) REFERENCES [dbo].[SAPO_ZWFOT32] ([OT32_ROWID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MOVEMENTLN]
  ADD CONSTRAINT [FK_MOVEMENTLN_SAPO_ZWFOT33] FOREIGN KEY ([MOL_OT33ID]) REFERENCES [dbo].[SAPO_ZWFOT33] ([OT33_ROWID]) ON DELETE CASCADE
GO