CREATE TABLE [dbo].[PAYTYPE] (
  [PAY_ROWID] [int] IDENTITY,
  [PAY_CODE] [nvarchar](30) NOT NULL,
  [PAY_ORG] [nvarchar](30) NOT NULL,
  [PAY_DESC] [nvarchar](80) NULL,
  [PAY_DAY] [int] NULL,
  CONSTRAINT [PK_PAYTYPE_1] PRIMARY KEY NONCLUSTERED ([PAY_CODE], [PAY_ORG]),
  CONSTRAINT [UQ_PAYTYPE] UNIQUE CLUSTERED ([PAY_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYTYPE]
  ADD CONSTRAINT [FK_PAYTYPE_ORG] FOREIGN KEY ([PAY_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE]) ON UPDATE CASCADE
GO