CREATE TABLE [dbo].[MRC] (
  [MRC_ROWID] [int] IDENTITY,
  [MRC_CODE] [nvarchar](30) NOT NULL,
  [MRC_ORG] [nvarchar](30) NOT NULL,
  [MRC_DESC] [nvarchar](255) NULL,
  [MRC_STATUS] [nvarchar](30) NULL,
  [MRC_RSTATUS] [int] NULL,
  [MRC_NOTUSED] [int] NULL,
  [MRC_JOBID] [nvarchar](30) NULL,
  [MRC_PRODID] [nvarchar](30) NULL,
  [MRC_NUMBER] [nvarchar](30) NULL,
  CONSTRAINT [PK_MRC_1] PRIMARY KEY CLUSTERED ([MRC_CODE]),
  CONSTRAINT [IX_MRC] UNIQUE ([MRC_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[MRC]
  ADD CONSTRAINT [FK_MRC_ORG] FOREIGN KEY ([MRC_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE]) ON UPDATE CASCADE
GO