CREATE TABLE [dbo].[OBJTECHPROTCHECK_GU] (
  [POC_ROWID] [int] IDENTITY,
  [POC_POTID] [int] NULL,
  [POC_GROUPID] [nvarchar](20) NOT NULL,
  [POC_CHECKUSER] [nvarchar](30) NULL,
  [POC_CREUSER] [nvarchar](30) NULL,
  [POC_CREDATE] [datetime] NULL CONSTRAINT [DF_OBJTECHPROTCHECK_GU_POC_CREDATE] DEFAULT (getdate()),
  [POC_UPDUSER] [nvarchar](30) NULL,
  [POC_UPDDATE] [datetime] NULL,
  [POC_CHECKDATE] [datetime] NULL,
  CONSTRAINT [PK_OBJTECHPROTCHECK_GU] PRIMARY KEY CLUSTERED ([POC_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[OBJTECHPROTCHECK_GU]
  ADD CONSTRAINT [FK_OBJTECHPROTCHECK_GU_GROUPID] FOREIGN KEY ([POC_GROUPID]) REFERENCES [dbo].[SYGroups] ([GroupID])
GO