CREATE TABLE [dbo].[SAPO_ZWFOT33LN] (
  [OT33LN_ROWID] [int] IDENTITY,
  [OT33LN_LP] [int] NULL,
  [OT33LN_BUKRS] [nvarchar](4) NULL,
  [OT33LN_ANLN1] [nvarchar](30) NULL,
  [OT33LN_TXT50] [nvarchar](50) NULL,
  [OT33LN_UZASADNIENIE] [nvarchar](50) NULL,
  [OT33LN_DT_WYDANIA] [datetime] NULL,
  [OT33LN_MPK_WYDANIA] [nvarchar](30) NULL,
  [OT33LN_GDLGRP] [nvarchar](30) NULL,
  [OT33LN_ZMT_ROWID] [int] NULL,
  [OT33LN_OT33ID] [int] NULL,
  [OT33LN_ANLN1_POSKI] [nvarchar](30) NULL,
  [OT33LN_MPK_WYDANIA_POSKI] [nvarchar](30) NULL,
  [OT33LN_GDLGRP_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT33LN] PRIMARY KEY CLUSTERED ([OT33LN_ROWID])
)
ON [PRIMARY]
GO