CREATE TABLE [dbo].[MAILRECIPIENTS] (
  [ROWID] [int] IDENTITY,
  [MAIR_MAISID] [int] NULL,
  [MAIR_EMPID] [int] NULL,
  [MAIR_QUERY] [nvarchar](max) NULL,
  CONSTRAINT [PK_MAILRECIPIENTS] PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MAILRECIPIENTS]
  ADD CONSTRAINT [FK_MAILRECIPIENTS_EMP] FOREIGN KEY ([MAIR_EMPID]) REFERENCES [dbo].[EMP] ([EMP_ROWID])
GO

ALTER TABLE [dbo].[MAILRECIPIENTS]
  ADD CONSTRAINT [FK_MAILRECIPIENTS_MAILSETTINGS] FOREIGN KEY ([MAIR_MAISID]) REFERENCES [dbo].[MAILSETTINGS] ([ROWID])
GO