CREATE TABLE [dbo].[SAPO_PMLN] (
  [PMLN_ROWID] [int] IDENTITY,
  [PMLN_PMID] [int] NOT NULL,
  [PMLN_COL_NAME] [nvarchar](30) NULL,
  [PMLN_COL_VALUE] [nvarchar](80) NULL,
  CONSTRAINT [PK_SAPO_PMLN] PRIMARY KEY CLUSTERED ([PMLN_ROWID])
)
ON [PRIMARY]
GO