CREATE TABLE [dbo].[ZWFOT_TEMPLATE] (
  [ROWID] [int] IDENTITY,
  [USERID] [nvarchar](30) NOT NULL,
  [OTID] [int] NOT NULL,
  [ACTIVE] [tinyint] NOT NULL CONSTRAINT [DF_ZWFOT_TEMPLATE_ACTIVE] DEFAULT (0),
  [NAME] [nvarchar](30) NULL,
  CONSTRAINT [PK_ZWFOT_TEMPLATE] PRIMARY KEY CLUSTERED ([USERID], [OTID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZWFOT_TEMPLATE]
  ADD CONSTRAINT [FK_ZWFOT_TEMPLATE_ZWFOT] FOREIGN KEY ([OTID]) REFERENCES [dbo].[ZWFOT] ([OT_ROWID]) ON DELETE CASCADE
GO