CREATE TABLE [dbo].[IE2_EQUI__RBNR] (
  [ROWID] [bigint] IDENTITY,
  [i_DateTime] [datetime] NOT NULL,
  [RBNR] [nvarchar](30) NULL,
  [RBNRX] [nvarchar](30) NULL,
  [DOC_NEW_INSERTED] [smallint] NULL DEFAULT (1),
  CONSTRAINT [PK_EQUI__RBNR] PRIMARY KEY NONCLUSTERED ([ROWID])
)
ON [PRIMARY]
GO

CREATE INDEX [PG_20190118]
  ON [dbo].[IE2_EQUI__RBNR] ([DOC_NEW_INSERTED])
  INCLUDE ([ROWID], [RBNR], [RBNRX])
  ON [PRIMARY]
GO