CREATE TABLE [dbo].[INSTRUKCJE] (
  [INS_ROWID] [int] IDENTITY,
  [INS_CODE] [nvarchar](30) NOT NULL,
  [INS_DESC] [nvarchar](max) NULL,
  [INS_FILEID2] [nvarchar](50) NULL,
  CONSTRAINT [PK_INSTRUKCJE] PRIMARY KEY CLUSTERED ([INS_CODE])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO