CREATE TABLE [dbo].[SAPO_ZWFOT33CHAR] (
  [OT33CHAR_ROWID] [int] IDENTITY,
  [OT33CHAR_LP] [int] NULL,
  [OT33CHAR_ANLN2] [nvarchar](4) NULL,
  [OT33CHAR_METAL] [nvarchar](15) NULL,
  [OT33CHAR_KATALIZATOR] [nvarchar](18) NULL,
  [OT33CHAR_METAL_OPIS] [nvarchar](50) NULL,
  [OT33CHAR_WSK_IL_METAL] [nvarchar](1) NULL,
  [OT33CHAR_MENGE] [decimal](13, 3) NULL,
  [OT33CHAR_MEINS] [nvarchar](3) NULL,
  [OT33CHAR_RODZ_IL_METAL] [nvarchar](10) NULL,
  [OT33CHAR_WSK_KW_METAL] [nvarchar](1) NULL,
  [OT33CHAR_KW_METAL] [decimal](13, 2) NULL,
  [OT33CHAR_RODZ_KW_METAL] [nvarchar](10) NULL,
  [OT33CHAR_ZRODLO] [nvarchar](30) NULL,
  [OT33CHAR_OPIS] [nvarchar](50) NULL,
  [OT33CHAR_AEDAT] [datetime] NULL,
  [OT33CHAR_AEZET] [time] NULL,
  [OT33CHAR_AENAM] [nvarchar](12) NULL,
  [OT33CHAR_ZAL] [nvarchar](30) NULL,
  [OT33CHAR_ILOSC_NOWA] [decimal](13, 3) NULL,
  [OT33CHAR_KW_NOWA] [decimal](13, 2) NULL,
  [OT33CHAR_ZMT_ROWID] [int] NULL,
  [OT33CHAR_OT33ID] [int] NULL,
  CONSTRAINT [PK_SAPO_ZWFOT33CHAR] PRIMARY KEY CLUSTERED ([OT33CHAR_ROWID])
)
ON [PRIMARY]
GO