CREATE TABLE [dbo].[OBJTECHPROTCHECK] (
  [POC_ROWID] [int] IDENTITY,
  [POC_POTID] [int] NULL,
  [POC_OBGID] [int] NULL,
  [POC_CHECKUSER] [nvarchar](30) NULL,
  [POC_CREUSER] [nvarchar](30) NULL,
  [POC_CREDATE] [datetime] NULL CONSTRAINT [DF_OBJTECHPROTCHECK_POC_CREDATE] DEFAULT (getdate()),
  [POC_UPDUSER] [nvarchar](30) NULL,
  [POC_UPDDATE] [datetime] NULL,
  [POC_CHECKDATE] [datetime] NULL,
  CONSTRAINT [PK_OBJTECHPROTCHECK] PRIMARY KEY CLUSTERED ([POC_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[OBJTECHPROTCHECK]
  ADD CONSTRAINT [FK_OBJTECHPROTCHECK_MOVEMENT] FOREIGN KEY ([POC_POTID]) REFERENCES [dbo].[OBJTECHPROT] ([POT_ROWID])
GO

ALTER TABLE [dbo].[OBJTECHPROTCHECK]
  ADD CONSTRAINT [FK_OBJTECHPROTCHECK_OBJGROUP] FOREIGN KEY ([POC_OBGID]) REFERENCES [dbo].[OBJGROUP] ([OBG_ROWID])
GO