CREATE TABLE [dbo].[ST_INW] (
  [SIN_ROWID] [int] IDENTITY,
  [SIN_CODE] [nvarchar](30) NOT NULL,
  [SIN_ORG] [nvarchar](30) NOT NULL,
  [SIN_STNID] [int] NULL,
  [SIN_CCDID] [int] NULL,
  [SIN_DESC] [nvarchar](80) NULL,
  [SIN_NOTE] [ntext] NULL,
  [SIN_DATE] [datetime] NULL,
  [SIN_STATUS] [nvarchar](30) NULL,
  [SIN_TYPE] [nvarchar](30) NULL,
  [SIN_TYPE2] [nvarchar](30) NULL,
  [SIN_TYPE3] [nvarchar](30) NULL,
  [SIN_RSTATUS] [int] NULL CONSTRAINT [DF_ST_INW_SIN_RSTATUS] DEFAULT (0),
  [SIN_CREUSER] [nvarchar](30) NULL CONSTRAINT [DF_ST_INW_SIN_CREUSER] DEFAULT ('SA'),
  [SIN_CREDATE] [datetime] NULL CONSTRAINT [DF_st_inw_CREDATE] DEFAULT (getdate()),
  [SIN_UPDUSER] [nvarchar](30) NULL,
  [SIN_UPDDATE] [datetime] NULL,
  [SIN_NOTUSED] [int] NULL CONSTRAINT [DF_ST_INW_SIN_NOTUSED] DEFAULT (0),
  [SIN_ID] [nvarchar](50) NULL CONSTRAINT [DF_st_inw_ID] DEFAULT (CONVERT([nvarchar](50),newid(),(0))),
  [SIN_TXT01] [nvarchar](30) NULL,
  [SIN_TXT02] [nvarchar](30) NULL,
  [SIN_TXT03] [nvarchar](30) NULL,
  [SIN_TXT04] [nvarchar](30) NULL,
  [SIN_TXT05] [nvarchar](30) NULL,
  [SIN_TXT06] [nvarchar](80) NULL,
  [SIN_TXT07] [nvarchar](80) NULL,
  [SIN_TXT08] [nvarchar](255) NULL,
  [SIN_TXT09] [nvarchar](255) NULL,
  [SIN_NTX01] [numeric](24, 6) NULL,
  [SIN_NTX02] [numeric](24, 6) NULL,
  [SIN_NTX03] [numeric](24, 6) NULL,
  [SIN_NTX04] [numeric](24, 6) NULL,
  [SIN_NTX05] [numeric](24, 6) NULL,
  [SIN_COM01] [ntext] NULL,
  [SIN_COM02] [ntext] NULL,
  [SIN_DTX01] [datetime] NULL,
  [SIN_DTX02] [datetime] NULL,
  [SIN_DTX03] [datetime] NULL,
  [SIN_DTX04] [datetime] NULL,
  [SIN_DTX05] [datetime] NULL,
  [SIN_AXAID] [bigint] NULL,
  [SIN_MAGID] [int] NULL,
  [SIN_RESPON] [nvarchar](30) NULL,
  [SIN_AUTH] [nvarchar](30) NULL,
  [SIN_AUTHDATE] [datetime] NULL,
  [SIN_BTN_ENABLE] [int] NULL,
  [SIN_AST] [smallint] NULL,
  [SIN_ROWGUID] [uniqueidentifier] NULL,
  [SIN_KL5ID] [int] NULL,
  [SIN_OS_MAT_ODP] [nvarchar](30) NULL,
  [SIN_WG_STAN_DZIEN] [datetime] NULL,
  [SIN_DOD_INDENTY] [nvarchar](30) NULL,
  [SIN_SPIS_START] [datetime] NULL,
  [SIN_SPIS_END] [datetime] NULL,
  [SIN_DEVICE_USER] [nvarchar](30) NULL,
  [SIN_COMMITTEE_MEMBER_1] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_2] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_3] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_4] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_5] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_6] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_7] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_8] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_9] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_10] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_11] [nvarchar](80) NULL,
  [SIN_COMMITTEE_MEMBER_12] [nvarchar](80) NULL,
  CONSTRAINT [PK_ST_INW] PRIMARY KEY NONCLUSTERED ([SIN_CODE], [SIN_ORG]),
  CONSTRAINT [UQ_ST_INW] UNIQUE CLUSTERED ([SIN_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ST_INW]
  ADD CONSTRAINT [FK_ST_INW_ORG] FOREIGN KEY ([SIN_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE])
GO

ALTER TABLE [dbo].[ST_INW]
  ADD CONSTRAINT [FK_ST_INW_ST_MAG] FOREIGN KEY ([SIN_MAGID]) REFERENCES [dbo].[ST_MAG] ([ROWID])
GO