CREATE TABLE [dbo].[CLASS] (
  [CLS_ENT] [nvarchar](10) NOT NULL,
  [CLS_CODE] [nvarchar](8) NOT NULL,
  [CLS_DESC] [nvarchar](80) NULL,
  [CLS_ORG] [nvarchar](15) NOT NULL,
  [CLS_LEVEL] [numeric](4) NULL,
  [CLS_UPDATECOUNT] [numeric](38) NULL DEFAULT (0),
  [CLS_CREATED] [datetime] NULL,
  [CLS_UPDATED] [datetime] NULL,
  [CLS_ROWID] [int] IDENTITY,
  [CLS_NOTUSED] [nvarchar](1) NULL DEFAULT (N'-'),
  [CLS_ICON] [nvarchar](30) NULL,
  [CLS_ICONPATH] [nvarchar](1000) NULL,
  [CLS_ENTITY] [nvarchar](10) NULL,
  CONSTRAINT [PRIK_CLS] PRIMARY KEY NONCLUSTERED ([CLS_ENT], [CLS_CODE]),
  CONSTRAINT [UNQ1_CLS] UNIQUE ([CLS_ENT], [CLS_CODE]),
  CONSTRAINT [UNQSQL_CLS] UNIQUE ([CLS_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASS] WITH NOCHECK
  ADD CONSTRAINT [CHK1_CLS] CHECK ([CLS_NOTUSED]=N'-' OR [CLS_NOTUSED]=N'+')
GO

ALTER TABLE [dbo].[CLASS] WITH NOCHECK
  ADD CONSTRAINT [NN01_CLS] CHECK ([CLS_ENT] IS NOT NULL)
GO

ALTER TABLE [dbo].[CLASS] WITH NOCHECK
  ADD CONSTRAINT [NN02_CLS] CHECK ([CLS_DESC] IS NOT NULL)
GO

ALTER TABLE [dbo].[CLASS] WITH NOCHECK
  ADD CONSTRAINT [FOK1_CLS] FOREIGN KEY ([CLS_ENT]) REFERENCES [dbo].[ENT] ([ENT_CODE])
GO