CREATE TABLE [dbo].[SAPIO_ActValuesHeaders] (
  [SAV_ROWID] [int] IDENTITY,
  [SAV_CODE] [nvarchar](30) NOT NULL,
  [SAV_TYPE] [nvarchar](30) NULL,
  [SAV_SASROWID] [int] NOT NULL,
  [SAV_ID] [nvarchar](50) NOT NULL CONSTRAINT [DF__SAPIO_Act__SAV_I__41021436] DEFAULT (CONVERT([nvarchar](50),newid())),
  [SAV_ENTITY] [nvarchar](30) NULL,
  [SAV_ENTID] [int] NULL,
  [SAV_UPDUSER] [nvarchar](30) NULL,
  [SAV_UPDDATE] [datetime] NULL,
  [SAV_CREUSER] [nvarchar](30) NOT NULL,
  [SAV_CREDATE] [datetime] NOT NULL CONSTRAINT [DF__SAPIO_Act__SAV_C__41F6386F] DEFAULT (getdate()),
  CONSTRAINT [PK__SAPIO_Ac__C51A432C16A34DA0] PRIMARY KEY CLUSTERED ([SAV_ROWID]),
  CONSTRAINT [UQ__SAPIO_Ac__1D09C30D4590B8F1] UNIQUE ([SAV_ID]),
  CONSTRAINT [UQ__SAPIO_Ac__9E3AB60A6EE0F6C2] UNIQUE ([SAV_CODE])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SAPIO_ActValuesHeaders]
  ADD CONSTRAINT [FK__SAPIO_Act__SAV_S__42EA5CA8] FOREIGN KEY ([SAV_SASROWID]) REFERENCES [dbo].[SAPIO_Statuses] ([SAS_ROWID]) ON UPDATE CASCADE
GO