CREATE TABLE [dbo].[IE2_ST_TEST] (
  [BUKRS] [nvarchar](30) NOT NULL,
  [ANLN1] [nvarchar](30) NULL,
  [ANLN2] [nvarchar](30) NULL,
  [ANLKL] [nvarchar](30) NOT NULL,
  [GEGST] [nvarchar](30) NULL,
  [ERNAM] [nvarchar](30) NULL,
  [ERDAT] [nvarchar](30) NULL,
  [AENAM] [nvarchar](30) NULL,
  [AEDAT] [nvarchar](30) NULL,
  [KTOGR] [nvarchar](30) NULL,
  [ANLTP] [nvarchar](30) NULL,
  [ZUJHR] [nvarchar](30) NULL,
  [ZUPER] [nvarchar](30) NULL,
  [ZUGDT] [nvarchar](30) NULL,
  [AKTIV] [nvarchar](30) NULL,
  [ABGDT] [nvarchar](30) NULL,
  [DEAKT] [nvarchar](30) NULL,
  [GPLAB] [nvarchar](30) NULL,
  [BSTDT] [nvarchar](30) NULL,
  [ORD41] [nvarchar](30) NULL,
  [ORD42] [nvarchar](30) NULL,
  [ORD43] [nvarchar](30) NULL,
  [ORD44] [nvarchar](30) NULL,
  [ANEQK] [nvarchar](30) NULL,
  [LIFNR] [nvarchar](30) NULL,
  [LAND1] [nvarchar](30) NULL,
  [LIEFE] [nvarchar](30) NULL,
  [HERST] [nvarchar](30) NULL,
  [EIGKZ] [nvarchar](30) NULL,
  [URWRT] [nvarchar](30) NULL,
  [ANTEI] [nvarchar](30) NULL,
  [MEINS] [nvarchar](30) NULL,
  [MENGE] [nvarchar](30) NULL,
  [VMGLI] [nvarchar](30) NULL,
  [XVRMW] [nvarchar](30) NULL,
  [WRTMA] [nvarchar](30) NULL,
  [EHWRT] [nvarchar](30) NULL,
  [STADT] [nvarchar](30) NULL,
  [GRUFL] [nvarchar](30) NULL,
  [VBUND] [nvarchar](30) NULL,
  [SPRAS] [nvarchar](30) NULL,
  [TXT50] [nvarchar](80) NULL,
  [GDLGRP] [nvarchar](30) NULL,
  [POSNR] [nvarchar](30) NULL,
  [KOSTL] [nvarchar](30) NULL,
  [WERKS] [nvarchar](30) NULL,
  [GSBER] [nvarchar](30) NULL
)
ON [PRIMARY]
GO