CREATE TABLE [dbo].[MAILBOX] (
  [ROWID] [int] IDENTITY,
  [MAIB_RECEIVER] [nvarchar](4000) NULL,
  [MAIB_USER] [nvarchar](4000) NULL,
  [MAIB_ORG] [nvarchar](50) NULL,
  [MAIB_SUBJECT] [nvarchar](500) NULL,
  [MAIB_BODY] [nvarchar](4000) NULL,
  [MAIB_ENT] [nvarchar](4) NULL,
  [MAIB_TYPE] [nvarchar](30) NULL,
  [MAIB_STATUS] [nvarchar](30) NULL,
  [MAIB_ISSEND] [int] NULL,
  [MAIB_SENDTIME] [datetime] NULL,
  [MAIB_CREATED] [datetime] NOT NULL CONSTRAINT [DF_E2EMAIBS_MAIB_CREATED] DEFAULT (getdate()),
  [MAIB_NROFRETRY] [int] NOT NULL CONSTRAINT [DF__E2EMAIBS__MAIB_N__37026115] DEFAULT (0),
  [MAIB_NRDOC] [nvarchar](80) NULL,
  [MAIB_MAISID] [int] NULL,
  [MAIB_QUERY] [nvarchar](max) NULL,
  [MAIB_MGTYPE] [nvarchar](50) NULL,
  [MAIB_DW] [nvarchar](500) NULL,
  [MAIB_REPORTNAME] [nvarchar](200) NULL,
  [MAIB_REPORTPARAMS] [nvarchar](200) NULL,
  [MAIB_ATTACHNAME] [nvarchar](200) NULL,
  [MAIB_ATTACH] [image] NULL,
  [MAIB_STATUS_IM] [nvarchar](20) NULL,
  CONSTRAINT [PK_EMAIBS] PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MAILBOX]
  ADD CONSTRAINT [FK_MAILBOX_MAILSETTINGS] FOREIGN KEY ([MAIB_MAISID]) REFERENCES [dbo].[MAILSETTINGS] ([ROWID])
GO