CREATE TABLE [dbo].[SAPO_ZWFOT40LN] (
  [OT40LN_ROWID] [int] IDENTITY,
  [OT40LN_BUKRS] [nvarchar](30) NULL,
  [OT40LN_ANLN1] [nvarchar](40) NULL,
  [OT40LN_ANLN2] [nvarchar](4) NULL,
  [OT40LN_PROC] [decimal](10, 2) NULL,
  [OT40LN_OPIS] [nvarchar](50) NULL,
  [OT40LN_ZMT_ROWID] [int] NULL,
  [OT40LN_OT40ID] [int] NULL,
  [OT40LN_ANLN1_POSKI] [nvarchar](30) NULL,
  CONSTRAINT [PK_SAPO_ZWFOT40LN] PRIMARY KEY CLUSTERED ([OT40LN_ROWID])
)
ON [PRIMARY]
GO