CREATE TABLE [dbo].[IE2_ST] (
  [ROWID] [bigint] IDENTITY,
  [i_DateTime] [datetime] NOT NULL,
  [Active] [int] NOT NULL,
  [BUKRS] [nvarchar](30) NOT NULL,
  [ANLN1] [nvarchar](30) NULL,
  [ANLN2] [nvarchar](30) NULL,
  [ANLKL] [nvarchar](30) NOT NULL,
  [GEGST] [nvarchar](30) NULL,
  [ERNAM] [nvarchar](30) NULL,
  [ERDAT] [datetime] NULL,
  [AENAM] [nvarchar](30) NULL,
  [AEDAT] [nvarchar](30) NULL,
  [KTOGR] [nvarchar](30) NULL,
  [ANLTP] [nvarchar](30) NULL,
  [ZUJHR] [nvarchar](30) NULL,
  [ZUPER] [nvarchar](30) NULL,
  [ZUGDT] [datetime] NULL,
  [AKTIV] [datetime] NULL,
  [ABGDT] [datetime] NULL,
  [DEAKT] [datetime] NULL,
  [GPLAB] [datetime] NULL,
  [BSTDT] [datetime] NULL,
  [ORD41] [nvarchar](30) NULL,
  [ORD42] [nvarchar](30) NULL,
  [ORD43] [nvarchar](30) NULL,
  [ORD44] [nvarchar](30) NULL,
  [ANEQK] [nvarchar](30) NULL,
  [LIFNR] [nvarchar](30) NULL,
  [LAND1] [nvarchar](30) NULL,
  [LIEFE] [nvarchar](30) NULL,
  [HERST] [nvarchar](30) NULL,
  [EIGKZ] [nvarchar](30) NULL,
  [URWRT] [nvarchar](30) NULL,
  [ANTEI] [nvarchar](30) NULL,
  [MEINS] [nvarchar](30) NULL,
  [MENGE] [nvarchar](30) NULL,
  [VMGLI] [nvarchar](30) NULL,
  [XVRMW] [nvarchar](30) NULL,
  [WRTMA] [nvarchar](30) NULL,
  [EHWRT] [nvarchar](30) NULL,
  [STADT] [nvarchar](30) NULL,
  [GRUFL] [nvarchar](30) NULL,
  [VBUND] [nvarchar](30) NULL,
  [SPRAS] [nvarchar](30) NULL,
  [TXT50] [nvarchar](80) NULL,
  [KOSTL] [nvarchar](30) NULL,
  [WERKS] [nvarchar](30) NULL,
  [GSBER] [nvarchar](30) NULL,
  [POSNR] [nvarchar](30) NULL,
  [GDLGRP] [nvarchar](30) NULL,
  [DOC_IDENT] [nvarchar](30) NULL,
  [DOC_NUM] [nvarchar](30) NULL,
  [DOC_YEAR] [int] NULL,
  [DATA_WYST] [datetime] NULL,
  [OSOBA_WYST] [nvarchar](30) NULL,
  [DOC_NEW_INSERTED] [smallint] NULL DEFAULT (1),
  [POSKI] [nvarchar](50) NULL,
  [TYPBZ] [nvarchar](30) NULL,
  [NDJARPER] [nvarchar](100) NULL,
  [ANLUE] [nvarchar](30) NULL,
  [STATUS_INW] [nvarchar](30) NULL,
  CONSTRAINT [PK_IE2_ST] PRIMARY KEY CLUSTERED ([ROWID])
)
ON [PRIMARY]
GO