CREATE TABLE [dbo].[ZWFOTLN] (
  [OTL_ROWID] [int] IDENTITY,
  [OTL_OTID] [int] NOT NULL,
  [OTL_STATUS] [nvarchar](30) NULL,
  [OTL_RSTATUS] [int] NULL,
  [OTL_ID] [nvarchar](50) NULL CONSTRAINT [df_OTL_ID] DEFAULT (newid()),
  [OTL_ORG] [nvarchar](30) NULL,
  [OTL_CODE] [nvarchar](30) NULL,
  [OTL_TYPE] [nvarchar](30) NULL,
  [OTL_CREDATE] [datetime] NULL,
  [OTL_CREUSER] [nvarchar](30) NULL,
  [OTL_UPDUSER] [nvarchar](30) NULL,
  [OTL_UPDDATE] [datetime] NULL,
  [OTL_OBJID] [int] NULL,
  [OTL_NOTUSED] [int] NULL DEFAULT (0),
  [OTL_OTLID] [int] NULL,
  CONSTRAINT [PK_SAPO_ZWFOTLN] PRIMARY KEY CLUSTERED ([OTL_ROWID])
)
ON [PRIMARY]
GO

CREATE INDEX [E2IDX_OTL01]
  ON [dbo].[ZWFOTLN] ([OTL_OTID])
  ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZWFOTLN]
  ADD CONSTRAINT [FK_ZWFOT_ORG] FOREIGN KEY ([OTL_ORG]) REFERENCES [dbo].[ORG] ([ORG_CODE])
GO

ALTER TABLE [dbo].[ZWFOTLN]
  ADD CONSTRAINT [FK_ZWFOTLN_OBJ] FOREIGN KEY ([OTL_OBJID]) REFERENCES [dbo].[OBJ] ([OBJ_ROWID])
GO

ALTER TABLE [dbo].[ZWFOTLN]
  ADD CONSTRAINT [FK_ZWFOTLN_ZWFOT] FOREIGN KEY ([OTL_OTID]) REFERENCES [dbo].[ZWFOT] ([OT_ROWID])
GO