CREATE TABLE [dbo].[ASTOBJ_FILTER] (
  [OBJ_USERID] [nvarchar](30) NOT NULL,
  [OBJ_CODE] [nvarchar](30) NULL,
  [OBJ_DESC] [nvarchar](80) NULL,
  [OBJ_GROUP] [nvarchar](30) NULL,
  [OBJ_STATION] [int] NULL,
  [OBJ_TYPE] [nvarchar](30) NULL,
  [OBJ_ID] [nvarchar](50) NULL CONSTRAINT [DF_AST_OBJ_FILTER_ID] DEFAULT (CONVERT([nvarchar](50),newid(),(0))),
  [OBJ_CREUSER] [nvarchar](30) NULL CONSTRAINT [DF_AST_OBJ_FILTER_CREUSER] DEFAULT (N'SA'),
  [OBJ_CREDATE] [datetime] NULL CONSTRAINT [DF_AST_OBJ_FILTER_CREDATE] DEFAULT (getdate()),
  [OBJ_NOTUSED] [int] NULL CONSTRAINT [DF_AST_OBJ_FILTER_NOTUSED] DEFAULT (0),
  [OBJ_PSP] [nvarchar](30) NULL,
  [OBJ_ASSET] [nvarchar](30) NULL,
  [OBJ_STS_CODE] [nvarchar](50) NULL,
  CONSTRAINT [PK_ASTOBJ_FILTER] PRIMARY KEY CLUSTERED ([OBJ_USERID])
)
ON [PRIMARY]
GO