CREATE TABLE [dbo].[ADDSTSPROPERTIES] (
  [ASP_PROID] [int] NOT NULL,
  [ASP_ENT] [nvarchar](10) NOT NULL,
  [ASP_STSID] [int] NOT NULL,
  [ASP_UOMID] [int] NULL,
  [ASP_LIST] [nchar](1) NULL,
  [ASP_UPDATECOUNT] [numeric](38) NULL DEFAULT (0),
  [ASP_CREATED] [datetime] NULL DEFAULT (getdate()),
  [ASP_UPDATED] [datetime] NULL DEFAULT (getdate()),
  [ASP_ROWID] [int] IDENTITY,
  [ASP_REQUIRED] [nvarchar](3) NULL,
  [ASP_VALUE] [nvarchar](512) NULL,
  CONSTRAINT [PRIK_ASP] PRIMARY KEY NONCLUSTERED ([ASP_PROID], [ASP_STSID]),
  CONSTRAINT [UNQSQL_ASP] UNIQUE ([ASP_ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADDSTSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [CHK1_ASP] CHECK ([ASP_list]=N'T' OR [ASP_list]=N'C' OR [ASP_list]=N'E' OR [ASP_list]=N'P' OR [ASP_list]=N'-')
GO

ALTER TABLE [dbo].[ADDSTSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [CHK3_ASP] CHECK ([ASP_REQUIRED]=N'TAK' OR [ASP_REQUIRED]=N'NIE')
GO

ALTER TABLE [dbo].[ADDSTSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK1_ASP] FOREIGN KEY ([ASP_STSID]) REFERENCES [dbo].[STENCIL] ([STS_ROWID])
GO

ALTER TABLE [dbo].[ADDSTSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK2_ASP] FOREIGN KEY ([ASP_PROID]) REFERENCES [dbo].[PROPERTIES] ([PRO_ROWID])
GO

ALTER TABLE [dbo].[ADDSTSPROPERTIES] WITH NOCHECK
  ADD CONSTRAINT [FOK3_ASP] FOREIGN KEY ([ASP_UOMID]) REFERENCES [dbo].[UOM] ([UOM_ROWID])
GO