CREATE TABLE [dbo].[RGBCOLOURS] (
  [ROWID] [int] IDENTITY,
  [RGB_CODE] [nvarchar](30) NOT NULL,
  [RGB_DESC] [nvarchar](80) NULL,
  [RGB_ENGNAME] [nvarchar](30) NULL,
  [RGB_R] [int] NULL,
  [RGB_G] [int] NULL,
  [RGB_B] [int] NULL,
  [RGB_NOTUSED] [int] NULL CONSTRAINT [DF_RGBCOLOURS_RGB_NOTUSED] DEFAULT (0),
  CONSTRAINT [PK_RGBCOLOURS] PRIMARY KEY CLUSTERED ([RGB_CODE]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO