CREATE TABLE [dbo].[COMMENTS] (
  [COM_ROWID] [int] IDENTITY,
  [COM_ENTITY] [nvarchar](10) NOT NULL,
  [COM_ID] [nvarchar](50) NOT NULL,
  [COM_TEXT] [nvarchar](max) NULL,
  [COM_DATE] [datetime] NULL CONSTRAINT [DF_COMENTS_COM_DATE] DEFAULT (getdate()),
  [COM_USER] [nvarchar](30) NULL,
  CONSTRAINT [PK_COMENTS] PRIMARY KEY NONCLUSTERED ([COM_ROWID], [COM_ENTITY], [COM_ID]),
  CONSTRAINT [UQ_COMENTS] UNIQUE ([COM_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMMENTS]
  ADD CONSTRAINT [FK_COMMENTS_COMMENTS] FOREIGN KEY ([COM_ENTITY]) REFERENCES [dbo].[ENT] ([ENT_CODE])
GO