CREATE TABLE [dbo].[PRVSTA] (
  [ROWID] [int] IDENTITY,
  [PST_GROUP] [nvarchar](20) NOT NULL,
  [PST_ENTITY] [nvarchar](10) NOT NULL,
  [PST_OLDSTATUS] [nvarchar](30) NOT NULL,
  [PST_NEWSTATUS] [nvarchar](30) NOT NULL,
  [PST_DEFAULT] [int] NULL,
  CONSTRAINT [PK_PRVSTA] PRIMARY KEY CLUSTERED ([PST_GROUP], [PST_ENTITY], [PST_OLDSTATUS], [PST_NEWSTATUS])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRVSTA]
  ADD CONSTRAINT [FK_PRVSTA_SYGroups] FOREIGN KEY ([PST_GROUP]) REFERENCES [dbo].[SYGroups] ([GroupID]) ON DELETE CASCADE ON UPDATE CASCADE
GO