CREATE TABLE [dbo].[OBJTECHPROTLN_DELETED] (
  [POL_ROWID] [int] IDENTITY,
  [POL_POTID] [int] NOT NULL,
  [POL_CODE] [nvarchar](30) NOT NULL,
  [POL_ORG] [nvarchar](30) NULL,
  [POL_DESC] [nvarchar](150) NULL,
  [POL_NOTE] [ntext] NULL,
  [POL_DATE] [datetime] NULL,
  [POL_STATUS] [nvarchar](30) NULL,
  [POL_TYPE] [nvarchar](30) NULL,
  [POL_TYPE2] [nvarchar](30) NULL,
  [POL_TYPE3] [nvarchar](30) NULL,
  [POL_RSTATUS] [int] NULL,
  [POL_CREUSER] [nvarchar](30) NULL,
  [POL_CREDATE] [datetime] NULL,
  [POL_UPDUSER] [nvarchar](30) NULL,
  [POL_UPDDATE] [datetime] NULL,
  [POL_NOTUSED] [int] NULL,
  [POL_ID] [nvarchar](50) NULL,
  [POL_TXT01] [nvarchar](30) NULL,
  [POL_TXT02] [nvarchar](30) NULL,
  [POL_TXT03] [nvarchar](30) NULL,
  [POL_TXT04] [nvarchar](30) NULL,
  [POL_TXT05] [nvarchar](30) NULL,
  [POL_TXT06] [nvarchar](80) NULL,
  [POL_TXT07] [nvarchar](80) NULL,
  [POL_TXT08] [nvarchar](255) NULL,
  [POL_TXT09] [nvarchar](255) NULL,
  [POL_NTX01] [numeric](24, 6) NULL,
  [POL_NTX02] [numeric](24, 6) NULL,
  [POL_NTX03] [numeric](24, 6) NULL,
  [POL_NTX04] [numeric](24, 6) NULL,
  [POL_NTX05] [numeric](24, 6) NULL,
  [POL_COM01] [ntext] NULL,
  [POL_COM02] [ntext] NULL,
  [POL_DTX01] [datetime] NULL,
  [POL_DTX02] [datetime] NULL,
  [POL_DTX03] [datetime] NULL,
  [POL_DTX04] [datetime] NULL,
  [POL_DTX05] [datetime] NULL,
  [POL_OBJID] [int] NULL,
  [POL_OLDQTY] [numeric](30, 6) NULL,
  [POL_NEWQTY] [numeric](30, 6) NULL,
  [POL_PRICE] [numeric](30, 6) NULL,
  [POL_PARTIAL] [numeric](8, 2) NULL,
  [POL_TO_STNID] [int] NULL,
  [POL_OT33ID] [int] NULL,
  [POL_OT31ID] [int] NULL,
  [POL_OT42ID] [int] NULL,
  [POL_OT41ID] [int] NULL,
  [POL_OT32ID] [int] NULL,
  [POL_COM03] [ntext] NULL,
  [POL_PS_ACCEPT] [int] NULL,
  [POL_PS_COMMENT] [nvarchar](max) NULL,
  [POL_BIZ_DEC] [int] NULL,
  [POL_ADHOC] [int] NULL,
  [POL_LIKW_TYPE] [int] NULL,
  [POL_LIKW_ADHOC] [int] NULL,
  [POL_TECHDEC_TYPE] [int] NULL,
  [POL_WIEK] [int] NULL,
  [POL_PRZEBIEG] [nvarchar](30) NULL,
  [POL_TECHDEC_DESC] [nvarchar](max) NULL,
  [POL_ATTACH] [nvarchar](max) NULL,
  [POL_UMO_WART] [numeric](26, 8) NULL,
  [POL_MIN_ODSP] [numeric](26, 8) NULL,
  [POL_WART_ODSP] [numeric](26, 8) NULL,
  [POL_ZARZ_BIZ] [int] NULL,
  [POL_RECOMM] [nvarchar](30) NULL,
  [POL_BIZDEC_TYPE] [nvarchar](max) NULL,
  [POL_LIKWALL] [int] NULL,
  [POL_PARTIAL_DEC] [int] NULL,
  [POL_RATED_PERSON] [nvarchar](30) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO