CREATE TABLE [dbo].[VS_ReportItems] (
  [rowid] [int] IDENTITY,
  [schema] [nvarchar](30) NOT NULL,
  [LastUpdate] [datetime] NULL,
  [UpdateInfo] [nvarchar](255) NULL,
  [itemtype] [nvarchar](80) NOT NULL CONSTRAINT [DF_VS_ReportItems_itemtype] DEFAULT (''),
  [name] [nvarchar](80) NOT NULL CONSTRAINT [DF_VS_ReportItems_name] DEFAULT (''),
  [parent] [nvarchar](30) NULL,
  [defname] [nvarchar](80) NULL,
  [value] [nvarchar](512) NULL,
  [left] [nvarchar](80) NULL,
  [top] [nvarchar](80) NULL,
  [width] [nvarchar](80) NULL,
  [height] [nvarchar](80) NULL,
  [fontfamily] [nvarchar](80) NULL,
  [fontsize] [nvarchar](80) NULL,
  [fontweight] [nvarchar](80) NULL,
  [color] [nvarchar](80) NULL,
  [backcolor] [nvarchar](80) NULL,
  [paddingtop] [nvarchar](80) NULL,
  [paddingbottom] [nvarchar](80) NULL,
  [paddingleft] [nvarchar](80) NULL,
  [paddingright] [nvarchar](80) NULL,
  [bordercolor] [nvarchar](80) NULL,
  [borderstyle] [nvarchar](80) NULL,
  [textdecoration] [nvarchar](80) NULL,
  [fontalign] [nvarchar](80) NULL,
  [borderwidth] [nvarchar](80) NULL,
  [underline] [nvarchar](80) NULL,
  [zindex] [nvarchar](80) NULL,
  [UpdateUser] [nvarchar](100) NULL,
  [note] [nvarchar](4000) NULL,
  [note1] [nvarchar](4000) NULL,
  [note2] [nvarchar](4000) NULL,
  [note3] [nvarchar](4000) NULL,
  CONSTRAINT [PK_VS_ReportItems] PRIMARY KEY NONCLUSTERED ([schema], [itemtype], [name])
)
ON [PRIMARY]
GO